"""Tests for Moving cog (auto-generated by testing framework)."""

import pytest
from unittest.mock import MagicMock, AsyncMock, patch
import discord

from cogs import moving_cog
from cogs import utility_cog


class TestMoving:
    """Validate all commands exist and have required metadata."""

    def test_add_exists(self):
        """Verify add command exists on the cog."""
        assert hasattr(moving_cog.Moving, 'add')

    def test_add_has_help(self):
        """Verify add command has help text."""
        method = getattr(moving_cog.Moving, 'add')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_pcadd_exists(self):
        """Verify pcadd command exists on the cog."""
        assert hasattr(moving_cog.Moving, 'pcadd')

    def test_pcadd_has_help(self):
        """Verify pcadd command has help text."""
        method = getattr(moving_cog.Moving, 'pcadd')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_addhere_exists(self):
        """Verify addhere command exists on the cog."""
        assert hasattr(moving_cog.Moving, 'addhere')

    def test_addhere_has_help(self):
        """Verify addhere command has help text."""
        method = getattr(moving_cog.Moving, 'addhere')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_remove_exists(self):
        """Verify remove command exists on the cog."""
        assert hasattr(moving_cog.Moving, 'remove')

    def test_remove_has_help(self):
        """Verify remove command has help text."""
        method = getattr(moving_cog.Moving, 'remove')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_pcremove_exists(self):
        """Verify pcremove command exists on the cog."""
        assert hasattr(moving_cog.Moving, 'pcremove')

    def test_pcremove_has_help(self):
        """Verify pcremove command has help text."""
        method = getattr(moving_cog.Moving, 'pcremove')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_move_exists(self):
        """Verify move command exists on the cog."""
        assert hasattr(moving_cog.Moving, 'move')

    def test_move_has_help(self):
        """Verify move command has help text."""
        method = getattr(moving_cog.Moving, 'move')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_renmove_exists(self):
        """Verify renmove command exists on the cog."""
        assert hasattr(moving_cog.Moving, 'renmove')

    def test_renmove_has_help(self):
        """Verify renmove command has help text."""
        method = getattr(moving_cog.Moving, 'renmove')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_knock_exists(self):
        """Verify knock command exists on the cog."""
        assert hasattr(moving_cog.Moving, 'knock')

    def test_knock_has_help(self):
        """Verify knock command has help text."""
        method = getattr(moving_cog.Moving, 'knock')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_renknock_exists(self):
        """Verify renknock command exists on the cog."""
        assert hasattr(moving_cog.Moving, 'renknock')

    def test_renknock_has_help(self):
        """Verify renknock command has help text."""
        method = getattr(moving_cog.Moving, 'renknock')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_pendingknock_exists(self):
        """Verify pendingknock command exists on the cog."""
        assert hasattr(moving_cog.Moving, 'pendingknock')

    def test_pendingknock_has_help(self):
        """Verify pendingknock command has help text."""
        method = getattr(moving_cog.Moving, 'pendingknock')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0


# ── Deep tests for recent changes ────────────────────────────────────────────

import asyncio
from datetime import timedelta


def _run(coro):
    loop = asyncio.new_event_loop()
    try:
        return loop.run_until_complete(coro)
    finally:
        loop.close()


class TestPendingknockChanges:
    """Tests for pendingknock owner restriction and scope changes."""

    def test_owner_ids_defined(self):
        """Verify OWNER_IDS tuple exists and contains the expected IDs."""
        assert hasattr(moving_cog.Moving, 'OWNER_IDS')
        assert 450772749829537793 in moving_cog.Moving.OWNER_IDS
        assert 691180618402234399 in moving_cog.Moving.OWNER_IDS

    def test_owner_ids_has_two_entries(self):
        """Verify OWNER_IDS has exactly 2 entries."""
        assert len(moving_cog.Moving.OWNER_IDS) == 2

    def test_format_duration_seconds(self):
        """Verify _format_duration handles seconds-only."""
        cog = moving_cog.Moving(None)
        result = cog._format_duration(timedelta(seconds=45))
        assert result == "45s"

    def test_format_duration_minutes(self):
        """Verify _format_duration handles minutes."""
        cog = moving_cog.Moving(None)
        result = cog._format_duration(timedelta(minutes=3, seconds=20))
        assert result == "3m 20s"

    def test_format_duration_hours(self):
        """Verify _format_duration handles hours."""
        cog = moving_cog.Moving(None)
        result = cog._format_duration(timedelta(hours=2, minutes=15))
        assert result == "2h 15m 0s"

    def test_format_duration_days(self):
        """Verify _format_duration handles days."""
        cog = moving_cog.Moving(None)
        result = cog._format_duration(timedelta(days=1, hours=5))
        assert result == "1d 5h 0m"

    def test_format_duration_zero(self):
        """Verify _format_duration handles zero/negative."""
        cog = moving_cog.Moving(None)
        result = cog._format_duration(timedelta(seconds=0))
        assert result == "0s"

    def test_get_pending_knocks_single_guild(self):
        """Verify _get_pending_knocks with all_guilds=False only scans current guild."""
        cog = moving_cog.Moving(None)
        ctx = MagicMock()
        ctx.guild = MagicMock()
        ctx.guild.id = 999
        ctx.guild.categories = []

        result = _run(cog._get_pending_knocks(ctx, all_guilds=False))
        pending, scanned = result
        assert scanned == 1

    def test_send_warning_redirects_to_os_disc(self):
        """Verify _send_warning sends to overseer-discussion when channel exists."""
        cog = moving_cog.Moving(None)
        ctx = MagicMock()
        os_disc = MagicMock()
        os_disc.send = AsyncMock(return_value=MagicMock())
        ctx.send = AsyncMock()
        embed = MagicMock()
        view = MagicMock()

        with patch('cogs.moving_cog.discord.utils.get', return_value=os_disc):
            result = _run(cog._send_warning(ctx, embed, view))

        os_disc.send.assert_called_once_with(embed=embed, view=view)
        ctx.send.assert_called_once()
        assert view.message is not None

    def test_send_warning_fallback_to_rc(self):
        """Verify _send_warning falls back to ctx.send when no overseer-discussion."""
        cog = moving_cog.Moving(None)
        ctx = MagicMock()
        ctx.send = AsyncMock(return_value=MagicMock())
        embed = MagicMock()
        view = MagicMock()

        with patch('cogs.moving_cog.discord.utils.get', return_value=None):
            result = _run(cog._send_warning(ctx, embed, view))

        ctx.send.assert_called_once_with(embed=embed, view=view)
        assert view.message is not None

    def test_send_warning_no_redirect_message_when_no_os_disc(self):
        """Verify no redirect notice is sent when overseer-discussion doesn't exist."""
        cog = moving_cog.Moving(None)
        ctx = MagicMock()
        ctx.send = AsyncMock(return_value=MagicMock())
        embed = MagicMock()
        view = MagicMock()

        with patch('cogs.moving_cog.discord.utils.get', return_value=None):
            _run(cog._send_warning(ctx, embed, view))

        call_args = ctx.send.call_args
        assert call_args.kwargs.get('content') is None or call_args.args == ()


class TestHomeSendWarning:
    """Tests for home_cog._send_warning redirect."""

    def test_send_warning_exists(self):
        """Verify _send_warning method exists on Home cog."""
        from cogs import home_cog
        assert hasattr(home_cog.Home, '_send_warning')

    def test_send_warning_redirects(self):
        """Verify _send_warning sends to overseer-discussion."""
        from cogs import home_cog
        cog = home_cog.Home(None)
        ctx = MagicMock()
        os_disc = MagicMock()
        os_disc.send = AsyncMock(return_value=MagicMock())
        ctx.send = AsyncMock()
        embed = MagicMock()
        view = MagicMock()

        with patch('cogs.home_cog.discord.utils.get', return_value=os_disc):
            _run(cog._send_warning(ctx, embed, view))

        os_disc.send.assert_called_once_with(embed=embed, view=view)

    def test_send_warning_fallback(self):
        """Verify _send_warning falls back when no overseer-discussion."""
        from cogs import home_cog
        cog = home_cog.Home(None)
        ctx = MagicMock()
        ctx.send = AsyncMock(return_value=MagicMock())
        embed = MagicMock()
        view = MagicMock()

        with patch('cogs.home_cog.discord.utils.get', return_value=None):
            _run(cog._send_warning(ctx, embed, view))

        ctx.send.assert_called_once_with(embed=embed, view=view)


class TestUtilitySendWarning:
    """Tests for utility_cog._send_warning redirect."""

    def test_send_warning_exists(self):
        """Verify _send_warning method exists on Utility cog."""
        assert hasattr(utility_cog.Utility, '_send_warning')

    def test_send_warning_redirects(self):
        """Verify _send_warning sends to overseer-discussion."""
        cog = utility_cog.Utility(None)
        ctx = MagicMock()
        os_disc = MagicMock()
        os_disc.send = AsyncMock(return_value=MagicMock())
        ctx.send = AsyncMock()
        embed = MagicMock()
        view = MagicMock()

        with patch('cogs.utility_cog.discord.utils.get', return_value=os_disc):
            _run(cog._send_warning(ctx, embed, view))

        os_disc.send.assert_called_once_with(embed=embed, view=view)

    def test_send_warning_fallback(self):
        """Verify _send_warning falls back when no overseer-discussion."""
        cog = utility_cog.Utility(None)
        ctx = MagicMock()
        ctx.send = AsyncMock(return_value=MagicMock())
        embed = MagicMock()
        view = MagicMock()

        with patch('cogs.utility_cog.discord.utils.get', return_value=None):
            _run(cog._send_warning(ctx, embed, view))

        ctx.send.assert_called_once_with(embed=embed, view=view)
