"""Tests for Game Manager En cog (auto-generated by testing framework)."""

import os
import types
from datetime import datetime, timedelta, timezone
from unittest.mock import AsyncMock, MagicMock, patch

import pytest
import discord

from cogs import game_manager_en


def make_game(**overrides):
    """Build a dict-shaped game row with sensible defaults."""
    data = {
        "id": 1,
        "host_id": 100,
        "cohost_ids": "",
        "guild_id": "",
        "range_label": "2026-07-H1",
        "name": "Test Game",
        "description": "desc",
        "max_players": 10,
        "status": "pending",
        "discord_invite": "",
        "created_at": "2026-01-01T00:00:00+00:00",
    }
    data.update(overrides)
    return data


def make_player(**overrides):
    data = {"id": 1, "game_id": 1, "user_id": 555, "role": "player", "slot": 1}
    data.update(overrides)
    return data


@pytest.fixture
def db_path(tmp_path, monkeypatch):
    path = os.path.join(tmp_path, "test_calendar.db")
    monkeypatch.setattr(game_manager_en, "DB_PATH", path)
    game_manager_en.init_db()
    return path


def insert_game(db_path, **overrides):
    game = make_game(**overrides)
    with game_manager_en.get_db() as conn:
        conn.execute(
            "INSERT INTO Games (host_id, cohost_ids, guild_id, range_label, name, "
            "description, max_players, discord_invite, created_at) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
            (
                game["host_id"], game["cohost_ids"], game["guild_id"],
                game["range_label"], game["name"], game["description"],
                game["max_players"], game["discord_invite"], game["created_at"],
            ),
        )
    return game


class TestGameManagerEn:
    """Validate all commands exist and have required metadata."""

    def test_calendar_cmd_exists(self):
        """Verify calendar_cmd command exists on the cog."""
        assert hasattr(game_manager_en.GameManagerEn, 'calendar_cmd')

    def test_calendar_cmd_has_help(self):
        """Verify calendar_cmd command has help text."""
        method = getattr(game_manager_en.GameManagerEn, 'calendar_cmd')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_addgamewizardview_instantiates(self):
        """Verify AddGameWizardView view can be instantiated."""
        # AddGameWizardView — requires cog/bot context to instantiate
        pass

    def test_calendarview_instantiates(self):
        """Verify CalendarView view can be instantiated."""
        # CalendarView — requires cog/bot context to instantiate
        pass

    def test_gamedetailview_instantiates(self):
        """Verify GameDetailView view can be instantiated."""
        # GameDetailView — requires cog/bot context to instantiate
        pass

    def test_playerlistview_instantiates(self):
        """Verify PlayerlistView view can be instantiated."""
        # PlayerlistView — requires cog/bot context to instantiate
        pass


class TestInviteHelpers:
    """Unit tests for invite parsing and validation helpers."""

    def test_invite_code_from_urls(self):
        assert game_manager_en._invite_code("https://discord.gg/abc123") == "abc123"
        assert game_manager_en._invite_code("https://discord.com/invite/xyz") == "xyz"
        assert game_manager_en._invite_code("https://discordapp.com/invite/code_1") == "code_1"
        assert game_manager_en._invite_code("https://discord.gg/abc/") == "abc"

    def test_invite_code_from_bare_code(self):
        assert game_manager_en._invite_code("abcDEF123") == "abcDEF123"

    def test_invite_code_invalid(self):
        assert game_manager_en._invite_code("not a link") is None
        assert game_manager_en._invite_code("") is None

    @pytest.mark.asyncio
    async def test_check_invite_valid(self):
        bot = MagicMock()
        inv = MagicMock()
        inv.expires_at = None
        bot.fetch_invite = AsyncMock(return_value=inv)
        ok, label = await game_manager_en._check_invite(bot, "https://discord.gg/abc123")
        assert ok is True
        assert "Valid" in label

    @pytest.mark.asyncio
    async def test_check_invite_valid_with_future_expiry(self):
        bot = MagicMock()
        inv = MagicMock()
        inv.expires_at = datetime.now(timezone.utc) + timedelta(days=1)
        bot.fetch_invite = AsyncMock(return_value=inv)
        ok, label = await game_manager_en._check_invite(bot, "https://discord.gg/abc123")
        assert ok is True
        assert "expires" in label

    @pytest.mark.asyncio
    async def test_check_invite_past_expiry(self):
        bot = MagicMock()
        inv = MagicMock()
        inv.expires_at = datetime.now(timezone.utc) - timedelta(days=1)
        bot.fetch_invite = AsyncMock(return_value=inv)
        ok, label = await game_manager_en._check_invite(bot, "https://discord.gg/abc123")
        assert ok is False
        assert "expired" in label

    @pytest.mark.asyncio
    async def test_check_invite_expired(self):
        bot = MagicMock()
        bot.fetch_invite = AsyncMock(side_effect=discord.NotFound(MagicMock(), "gone"))
        ok, label = await game_manager_en._check_invite(bot, "https://discord.gg/abc123")
        assert ok is False

    @pytest.mark.asyncio
    async def test_check_invite_http_error(self):
        bot = MagicMock()
        bot.fetch_invite = AsyncMock(side_effect=discord.HTTPException(MagicMock(), "boom"))
        ok, label = await game_manager_en._check_invite(bot, "https://discord.gg/abc123")
        assert ok is None

    @pytest.mark.asyncio
    async def test_check_invite_unparsable(self):
        bot = MagicMock()
        ok, label = await game_manager_en._check_invite(bot, "not a link")
        assert ok is None
        assert "parse" in label


class TestParseIds:
    def test_parses_multiple(self):
        assert game_manager_en._parse_ids("123456789, 987654321") == [123456789, 987654321]

    def test_parses_mentions(self):
        assert game_manager_en._parse_ids("@user123456 @user654321") == [123456, 654321]

    def test_empty(self):
        assert game_manager_en._parse_ids("") == []

    def test_ignores_short_numbers(self):
        assert game_manager_en._parse_ids("12 12345 abc") == []


class TestPermissions:
    def test_is_host(self):
        game = make_game(host_id=100)
        assert game_manager_en._is_host(game, 100) is True
        assert game_manager_en._is_host(game, 101) is False

    def test_is_host_with_cohosts(self):
        game = make_game(host_id=100, cohost_ids="111111111, 222222222")
        assert game_manager_en._is_host(game, 111111111) is True
        assert game_manager_en._is_host(game, 222222222) is True

    def test_can_manage_host(self):
        game = make_game(host_id=100)
        assert game_manager_en._can_manage(game, 100) is True

    def test_can_manage_global_admin(self):
        game = make_game(host_id=100)
        with patch.object(game_manager_en, "GLOBAL_ADMINS", [999]):
            assert game_manager_en._can_manage(game, 999) is True

    def test_can_manage_denied(self):
        game = make_game(host_id=100)
        with patch.object(game_manager_en, "GLOBAL_ADMINS", []):
            assert game_manager_en._can_manage(game, 999) is False


class TestRangeLabel:
    def test_label_first_half(self):
        assert game_manager_en._range_label_from_value("2026-07-H1") == "July 2026 - First Half"

    def test_label_second_half(self):
        assert game_manager_en._range_label_from_value("2026-07-H2") == "July 2026 - Second Half"

    def test_label_invalid_returns_value(self):
        assert game_manager_en._range_label_from_value("weird") == "weird"

    def test_display_to_value_passthrough(self):
        assert game_manager_en._display_to_value("2026-07-H1") == "2026-07-H1"

    def test_display_to_value_first_half(self):
        assert game_manager_en._display_to_value("July 2026 - First Half") == "2026-07-H1"

    def test_display_to_value_second_half(self):
        assert game_manager_en._display_to_value("July 2026 - Second Half") == "2026-07-H2"


class TestStatusLabels:
    def test_emoji_mapping(self):
        assert game_manager_en._status_emoji("ongoing") == "🟢"
        assert game_manager_en._status_emoji("ended") == "🔴"
        assert game_manager_en._status_emoji("inviting") == "🚪"
        assert game_manager_en._status_emoji("canceled") == "❌"
        assert game_manager_en._status_emoji("pending") == "⏳"

    def test_emoji_unknown_default(self):
        assert game_manager_en._status_emoji(None) == "⏳"
        assert game_manager_en._status_emoji("bogus") == "⏳"

    def test_label_mapping(self):
        assert game_manager_en._status_label("ongoing") == "Ongoing"
        assert game_manager_en._status_label("inviting") == "Players Joining..."

    def test_label_unknown_default(self):
        assert game_manager_en._status_label("bogus") == "Pending"


class TestSafeGet:
    def test_returns_value(self):
        row = make_game(name="X")
        assert game_manager_en._safe_get(row, "name") == "X"

    def test_missing_key_returns_default(self):
        row = make_game()
        assert game_manager_en._safe_get(row, "nope") == ""
        assert game_manager_en._safe_get(row, "nope", "d") == "d"

    def test_falsy_value_returns_default(self):
        row = make_game(name="")
        assert game_manager_en._safe_get(row, "name") == ""


class TestCalendarEmbed:
    def test_empty(self):
        embed = game_manager_en.calendar_embed([])
        assert "No games scheduled" in embed.description

    def test_shows_invite_after_date(self):
        game = make_game(name="G1", range_label="2026-08-H1", discord_invite="https://discord.gg/abc")
        embed = game_manager_en.calendar_embed([game])
        assert "**G1**" in embed.description
        assert "August 2026 - First Half" in embed.description
        assert "🔗 https://discord.gg/abc" in embed.description

    def test_hides_invite_when_empty(self):
        game = make_game(name="G1", discord_invite="")
        embed = game_manager_en.calendar_embed([game])
        assert "🔗" not in embed.description

    def test_sorted_by_range(self):
        g1 = make_game(name="Later", range_label="2026-09-H1")
        g2 = make_game(name="Earlier", range_label="2026-06-H2")
        embed = game_manager_en.calendar_embed([g1, g2])
        assert embed.description.index("Earlier") < embed.description.index("Later")


class TestGameDetailEmbed:
    def test_fields_present(self):
        game = make_game(name="G1", range_label="2026-07-H1", status="pending",
                         description="hello", discord_invite="https://discord.gg/abc")
        embed = game_manager_en.game_detail_embed(game, MagicMock())
        values = {f.name: f.value for f in embed.fields}
        assert values["Date Range"] == "July 2026 - First Half"
        assert "Ongoing" not in values["Status"]
        assert values["Discord Invite"] == "https://discord.gg/abc"
        assert values["Description"] == "hello"
        assert values["Host"] == "<@100>"

    def test_invite_placeholder_when_missing(self):
        game = make_game(discord_invite="")
        embed = game_manager_en.game_detail_embed(game, MagicMock())
        values = {f.name: f.value for f in embed.fields}
        assert values["Discord Invite"] == "—"

    def test_default_name_when_blank(self):
        game = make_game(name="")
        embed = game_manager_en.game_detail_embed(game, MagicMock())
        assert embed.title == "🎮  Game #1"

    def test_cohosts_listed(self):
        game = make_game(cohost_ids="111111111, 222222222")
        embed = game_manager_en.game_detail_embed(game, MagicMock())
        values = {f.name: f.value for f in embed.fields}
        assert "<@111111111>" in values["Co-Hosts"]
        assert "<@222222222>" in values["Co-Hosts"]


class TestPlayerlistEmbed:
    def test_empty(self):
        embed = game_manager_en.playerlist_embed(make_game(max_players=0), [])
        assert "No players yet" in embed.description

    def test_players_and_sponsors(self):
        players = [
            make_player(user_id=555, role="player", slot=1),
            make_player(user_id=666, role="sponsor", slot=1),
            make_player(user_id=777, role="player", slot=2),
        ]
        embed = game_manager_en.playerlist_embed(make_game(max_players=2), players)
        assert "<@555>" in embed.description
        assert "<@666>" in embed.description
        assert "<@777>" in embed.description

    def test_empty_slots_shown(self):
        players = [make_player(user_id=555, role="player", slot=1)]
        embed = game_manager_en.playerlist_embed(make_game(max_players=2), players)
        assert "Empty" in embed.description


class TestDatabase:
    def test_init_db_creates_tables(self, db_path):
        with game_manager_en.get_db() as conn:
            tables = {r[0] for r in conn.execute("SELECT name FROM sqlite_master WHERE type='table'")}
        assert "Games" in tables
        assert "Players" in tables

    def test_init_db_idempotent(self, db_path):
        game_manager_en.init_db()
        with game_manager_en.get_db() as conn:
            tables = {r[0] for r in conn.execute("SELECT name FROM sqlite_master WHERE type='table'")}
        assert "Games" in tables

    def test_insert_and_read_game(self, db_path):
        insert_game(db_path, name="Real Game", range_label="2026-07-H2",
                    discord_invite="https://discord.gg/xyz")
        with game_manager_en.get_db() as conn:
            row = conn.execute("SELECT * FROM Games").fetchone()
        assert row["name"] == "Real Game"
        assert row["discord_invite"] == "https://discord.gg/xyz"

    def test_update_invite(self, db_path):
        insert_game(db_path)
        with game_manager_en.get_db() as conn:
            conn.execute("UPDATE Games SET discord_invite=? WHERE id=?", ("https://discord.gg/new", 1))
        with game_manager_en.get_db() as conn:
            row = conn.execute("SELECT * FROM Games WHERE id=1").fetchone()
        assert row["discord_invite"] == "https://discord.gg/new"


class TestAddGameDetailsModal:
    def _make_modal(self, db_path, invite_value="", name="Test Game",
                    max_players="10"):
        modal = object.__new__(game_manager_en.AddGameDetailsModal)
        modal.cog = MagicMock()
        modal.wizard = types.SimpleNamespace(
            cohost_raw="", guild_id_raw="", year=2026, month=8, half="H1",
            invoker_id=999, calendar_message=None,
        )
        modal.name_input = types.SimpleNamespace(value=name)
        modal.description = types.SimpleNamespace(value="Desc")
        modal.max_players = types.SimpleNamespace(value=max_players)
        modal.discord_invite = types.SimpleNamespace(value=invite_value)
        return modal

    def _make_interaction(self, user_id=100, fetch=None):
        inter = MagicMock()
        inter.user.id = user_id
        inter.client.fetch_invite = fetch or AsyncMock()
        inter.response.edit_message = AsyncMock()
        inter.response.send_message = AsyncMock()
        return inter

    @pytest.mark.asyncio
    async def test_valid_creates_game(self, db_path):
        modal = self._make_modal(db_path)
        inter = self._make_interaction()
        await modal.on_submit(inter)
        inter.response.edit_message.assert_awaited_once()
        with game_manager_en.get_db() as conn:
            row = conn.execute("SELECT * FROM Games").fetchone()
        assert row["name"] == "Test Game"
        assert row["range_label"] == "2026-08-H1"
        assert row["host_id"] == 100

    @pytest.mark.asyncio
    async def test_invalid_max_players_rejected(self, db_path):
        modal = self._make_modal(db_path, max_players="abc")
        inter = self._make_interaction()
        await modal.on_submit(inter)
        inter.response.send_message.assert_awaited_once()
        with game_manager_en.get_db() as conn:
            assert conn.execute("SELECT COUNT(*) FROM Games").fetchone()[0] == 0

    @pytest.mark.asyncio
    async def test_expired_invite_rejected(self, db_path):
        modal = self._make_modal(db_path, invite_value="https://discord.gg/expired")
        inter = self._make_interaction(
            fetch=AsyncMock(side_effect=discord.NotFound(MagicMock(), "gone"))
        )
        await modal.on_submit(inter)
        msg = inter.response.send_message.await_args[0][0]
        assert "valid, unexpired" in msg
        with game_manager_en.get_db() as conn:
            assert conn.execute("SELECT COUNT(*) FROM Games").fetchone()[0] == 0

    @pytest.mark.asyncio
    async def test_valid_invite_saved(self, db_path):
        inv = MagicMock()
        inv.expires_at = None
        modal = self._make_modal(db_path, invite_value="https://discord.gg/good")
        inter = self._make_interaction(fetch=AsyncMock(return_value=inv))
        await modal.on_submit(inter)
        with game_manager_en.get_db() as conn:
            row = conn.execute("SELECT * FROM Games").fetchone()
        assert row["discord_invite"] == "https://discord.gg/good"


class TestServerLinkModal:
    def _make_modal(self, db_path, game=None, invite_value="", cog=None):
        modal = object.__new__(game_manager_en.ServerLinkModal)
        modal.cog = cog or types.SimpleNamespace(show_game_detail=AsyncMock())
        modal.game = game or make_game(host_id=100, id=1)
        modal.invite_input = types.SimpleNamespace(value=invite_value)
        return modal

    @pytest.mark.asyncio
    async def test_valid_invite_saved(self, db_path):
        insert_game(db_path)
        inv = MagicMock()
        inv.expires_at = None
        modal = self._make_modal(db_path, invite_value="https://discord.gg/newlink")
        inter = MagicMock()
        inter.user.id = 100
        inter.client.fetch_invite = AsyncMock(return_value=inv)
        inter.response.defer = AsyncMock()
        inter.response.send_message = AsyncMock()
        await modal.on_submit(inter)
        with game_manager_en.get_db() as conn:
            row = conn.execute("SELECT * FROM Games WHERE id=1").fetchone()
        assert row["discord_invite"] == "https://discord.gg/newlink"
        modal.cog.show_game_detail.assert_awaited_once()

    @pytest.mark.asyncio
    async def test_expired_invite_rejected(self, db_path):
        insert_game(db_path)
        modal = self._make_modal(db_path, invite_value="https://discord.gg/expired")
        inter = MagicMock()
        inter.user.id = 100
        inter.client.fetch_invite = AsyncMock(side_effect=discord.NotFound(MagicMock(), "gone"))
        inter.response.defer = AsyncMock()
        inter.response.send_message = AsyncMock()
        await modal.on_submit(inter)
        msg = inter.response.send_message.await_args[0][0]
        assert "not saved" in msg
        with game_manager_en.get_db() as conn:
            row = conn.execute("SELECT * FROM Games WHERE id=1").fetchone()
        assert row["discord_invite"] == ""
        modal.cog.show_game_detail.assert_not_awaited()

    @pytest.mark.asyncio
    async def test_empty_clears_invite(self, db_path):
        insert_game(db_path, discord_invite="https://discord.gg/old")
        modal = self._make_modal(db_path, invite_value="")
        inter = MagicMock()
        inter.user.id = 100
        inter.response.defer = AsyncMock()
        inter.response.send_message = AsyncMock()
        await modal.on_submit(inter)
        with game_manager_en.get_db() as conn:
            row = conn.execute("SELECT * FROM Games WHERE id=1").fetchone()
        assert row["discord_invite"] == ""

    @pytest.mark.asyncio
    async def test_permission_denied(self, db_path):
        insert_game(db_path)
        modal = self._make_modal(db_path, invite_value="https://discord.gg/abc")
        inter = MagicMock()
        inter.user.id = 999
        inter.response.send_message = AsyncMock()
        await modal.on_submit(inter)
        msg = inter.response.send_message.await_args[0][0]
        assert "Permission denied" in msg
        with game_manager_en.get_db() as conn:
            row = conn.execute("SELECT * FROM Games WHERE id=1").fetchone()
        assert row["discord_invite"] == ""


class TestEditFieldModal:
    def _make_modal(self, db_path, field, value, game=None, user_id=100):
        modal = object.__new__(game_manager_en.EditFieldModal)
        modal.cog = types.SimpleNamespace(show_game_detail=AsyncMock())
        modal.game = game or make_game(host_id=100, id=1)
        modal.field = field
        modal.value_input = types.SimpleNamespace(value=value)
        return modal, user_id

    def _interaction(self, user_id=100):
        inter = MagicMock()
        inter.user.id = user_id
        inter.response.defer = AsyncMock()
        inter.response.send_message = AsyncMock()
        return inter

    @pytest.mark.asyncio
    async def test_range_update(self, db_path):
        insert_game(db_path, range_label="2026-07-H1")
        modal, uid = self._make_modal(db_path, "range", "July 2026 - First Half")
        inter = self._interaction(uid)
        await modal.on_submit(inter)
        with game_manager_en.get_db() as conn:
            row = conn.execute("SELECT * FROM Games WHERE id=1").fetchone()
        assert row["range_label"] == "2026-07-H1"
        modal.cog.show_game_detail.assert_awaited_once()

    @pytest.mark.asyncio
    async def test_max_players_valid(self, db_path):
        insert_game(db_path, max_players=10)
        modal, uid = self._make_modal(db_path, "max_players", "20")
        inter = self._interaction(uid)
        await modal.on_submit(inter)
        with game_manager_en.get_db() as conn:
            row = conn.execute("SELECT * FROM Games WHERE id=1").fetchone()
        assert row["max_players"] == 20

    @pytest.mark.asyncio
    async def test_max_players_invalid(self, db_path):
        insert_game(db_path, max_players=10)
        modal, uid = self._make_modal(db_path, "max_players", "abc")
        inter = self._interaction(uid)
        await modal.on_submit(inter)
        msg = inter.response.send_message.await_args[0][0]
        assert "positive integer" in msg
        with game_manager_en.get_db() as conn:
            row = conn.execute("SELECT * FROM Games WHERE id=1").fetchone()
        assert row["max_players"] == 10

    @pytest.mark.asyncio
    async def test_direct_field_update(self, db_path):
        insert_game(db_path, name="Old")
        modal, uid = self._make_modal(db_path, "name", "New Name")
        inter = self._interaction(uid)
        await modal.on_submit(inter)
        with game_manager_en.get_db() as conn:
            row = conn.execute("SELECT * FROM Games WHERE id=1").fetchone()
        assert row["name"] == "New Name"

    @pytest.mark.asyncio
    async def test_unknown_field(self, db_path):
        modal, uid = self._make_modal(db_path, "bogus", "x")
        inter = self._interaction(uid)
        await modal.on_submit(inter)
        msg = inter.response.send_message.await_args[0][0]
        assert "Unknown field" in msg

    @pytest.mark.asyncio
    async def test_permission_denied(self, db_path):
        insert_game(db_path, name="Old")
        modal, _ = self._make_modal(db_path, "name", "New", user_id=999)
        inter = self._interaction(999)
        await modal.on_submit(inter)
        msg = inter.response.send_message.await_args[0][0]
        assert "Permission denied" in msg
        with game_manager_en.get_db() as conn:
            row = conn.execute("SELECT * FROM Games WHERE id=1").fetchone()
        assert row["name"] == "Old"


class TestCoHostAndServerModal:
    @pytest.mark.asyncio
    async def test_on_submit_stores_values(self):
        wizard = MagicMock()
        wizard.month = 7
        wizard.year = 2026
        wizard.half = "H1"
        modal = object.__new__(game_manager_en.CoHostAndServerModal)
        modal.wizard = wizard
        modal.cohost_input = types.SimpleNamespace(value="@100123456 @200123456")
        modal.guild_id_input = types.SimpleNamespace(value="123456789012")
        inter = MagicMock()
        inter.response.edit_message = AsyncMock()
        await modal.on_submit(inter)
        assert modal.wizard.cohost_raw == "@100123456 @200123456"
        assert modal.wizard.guild_id_raw == "123456789012"
        wizard._build_cohost_step.assert_called_once()
        inter.response.edit_message.assert_awaited_once()


class TestAddGameWizardView:
    @pytest.mark.asyncio
    async def test_check_invoker_rejects_other_user(self):
        wizard = object.__new__(game_manager_en.AddGameWizardView)
        wizard.invoker_id = 100
        inter = MagicMock()
        inter.user.id = 200
        inter.response.send_message = AsyncMock()
        assert await wizard._check_invoker(inter) is False
        inter.response.send_message.assert_awaited_once()

    @pytest.mark.asyncio
    async def test_check_invoker_accepts_invoker(self):
        wizard = object.__new__(game_manager_en.AddGameWizardView)
        wizard.invoker_id = 100
        inter = MagicMock()
        inter.user.id = 100
        assert await wizard._check_invoker(inter) is True

    @pytest.mark.asyncio
    async def test_build_steps(self):
        wizard = game_manager_en.AddGameWizardView(MagicMock(), 100, None)
        assert len(wizard.children) == 1
        wizard.year = 2026
        wizard.month = 7
        wizard.half = "H1"
        wizard._build_month_select()
        assert len(wizard.children) == 1
        wizard._build_half_select()
        assert len(wizard.children) == 1
        wizard._build_cohost_step()
        assert len(wizard.children) == 2


class TestViews:
    @pytest.mark.asyncio
    async def test_calendar_view_empty(self, db_path):
        view = game_manager_en.CalendarView(MagicMock(), 100)
        embed = view.build_embed()
        assert "No games scheduled" in embed.description
        assert view._page_games == []

    @pytest.mark.asyncio
    async def test_calendar_view_pagination(self, db_path):
        for i in range(8):
            insert_game(db_path, id=i + 1, name=f"Game {i + 1}",
                        range_label=f"2026-{7 + i // 2:02d}-H{1 if i % 2 == 0 else 2}")
        view = game_manager_en.CalendarView(MagicMock(), 100, page=1)
        assert len(view._page_games) == 2
        view0 = game_manager_en.CalendarView(MagicMock(), 100, page=0)
        assert len(view0._page_games) == 6
        assert "No games scheduled" not in view.build_embed().description

    @pytest.mark.asyncio
    async def test_game_detail_view_non_manager(self):
        game = make_game(host_id=100, id=1)
        view = game_manager_en.GameDetailView(MagicMock(), game, invoker_id=999)
        labels = {c.label for c in view.children if getattr(c, "label", None)}
        assert "📋 Playerlist" in labels
        assert "⬅️ Back" in labels
        assert "🔗 Server Link" not in labels

    @pytest.mark.asyncio
    async def test_game_detail_view_manager_has_controls(self):
        game = make_game(host_id=100, id=1)
        view = game_manager_en.GameDetailView(MagicMock(), game, invoker_id=100)
        labels = {c.label for c in view.children if getattr(c, "label", None)}
        assert "🔗 Server Link" in labels
        emojis = {c.emoji.name for c in view.children if getattr(c, "emoji", None)}
        assert "🗑️" in emojis
        placeholders = {c.placeholder for c in view.children if getattr(c, "placeholder", None)}
        assert "🔄 Change Game Status…" in placeholders
        assert "✏️ Edit a field…" in placeholders

    @pytest.mark.asyncio
    async def test_playerlist_view(self, db_path):
        insert_game(db_path, max_players=10)
        game = make_game(host_id=100, id=1, max_players=10)
        view = game_manager_en.PlayerlistView(MagicMock(), game, invoker_id=999)
        placeholders = {c.placeholder for c in view.children if getattr(c, "placeholder", None)}
        assert any("role" in p for p in placeholders)

    @pytest.mark.asyncio
    async def test_playerlist_view_slot_select_when_role_chosen(self, db_path):
        game = make_game(host_id=100, id=1, max_players=10)
        view = game_manager_en.PlayerlistView(MagicMock(), game, invoker_id=999,
                                              chosen_role="player")
        placeholders = {c.placeholder for c in view.children if getattr(c, "placeholder", None)}
        assert any("slot" in p.lower() for p in placeholders)


class TestCog:
    @pytest.mark.asyncio
    async def test_show_calendar(self, db_path):
        cog = game_manager_en.GameManagerEn(MagicMock())
        inter = MagicMock()
        inter.user.id = 100
        inter.response.is_done.return_value = False
        inter.response.edit_message = AsyncMock()
        await cog.show_calendar(inter)
        inter.response.edit_message.assert_awaited_once()

    @pytest.mark.asyncio
    async def test_show_game_detail(self, db_path):
        cog = game_manager_en.GameManagerEn(MagicMock())
        inter = MagicMock()
        inter.user.id = 100
        inter.response.is_done.return_value = False
        inter.response.edit_message = AsyncMock()
        await cog.show_game_detail(inter, make_game(id=1))
        inter.response.edit_message.assert_awaited_once()

    @pytest.mark.asyncio
    async def test_show_playerlist(self, db_path):
        insert_game(db_path)
        cog = game_manager_en.GameManagerEn(MagicMock())
        inter = MagicMock()
        inter.user.id = 100
        inter.response.is_done.return_value = False
        inter.response.edit_message = AsyncMock()
        await cog.show_playerlist(inter, make_game(id=1))
        inter.response.edit_message.assert_awaited_once()

    @pytest.mark.asyncio
    async def test_calendar_cmd_sends(self, db_path):
        cog = game_manager_en.GameManagerEn(MagicMock())
        ctx = MagicMock()
        ctx.author.id = 100
        ctx.send = AsyncMock()
        await cog.calendar_cmd.callback(cog, ctx)
        ctx.send.assert_awaited_once()

    @pytest.mark.asyncio
    async def test_setup(self, db_path):
        bot = MagicMock()
        bot.add_cog = AsyncMock()
        await game_manager_en.setup(bot)
        bot.add_cog.assert_awaited_once()
