"""Tests for Library cog (auto-generated by testing framework)."""

import pytest
import sqlite3
import os
from unittest.mock import MagicMock, AsyncMock, patch
import discord

from cogs import library_cog


class TestGameLibrary:
    """Validate all commands exist and have required metadata."""

    def test_missing_ids_exists(self):
        assert hasattr(library_cog.GameLibrary, 'missing_ids')

    def test_missing_ids_has_help(self):
        method = getattr(library_cog.GameLibrary, 'missing_ids')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_stats_exists(self):
        assert hasattr(library_cog.GameLibrary, 'stats')

    def test_stats_has_help(self):
        method = getattr(library_cog.GameLibrary, 'stats')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_winrate_exists(self):
        assert hasattr(library_cog.GameLibrary, 'winrate')

    def test_winrate_has_help(self):
        method = getattr(library_cog.GameLibrary, 'winrate')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_relations_exists(self):
        assert hasattr(library_cog.GameLibrary, 'relations')

    def test_relations_has_help(self):
        method = getattr(library_cog.GameLibrary, 'relations')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_statsos_exists(self):
        assert hasattr(library_cog.GameLibrary, 'statsos')

    def test_statsos_has_help(self):
        method = getattr(library_cog.GameLibrary, 'statsos')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_lib_searchos_exists(self):
        """Verify lib command group has searchos subcommand."""
        lib_cmd = getattr(library_cog.GameLibrary, 'lib')
        assert lib_cmd is not None

    def test_overseerleaderboardview_class(self):
        assert hasattr(library_cog, 'OverseerLeaderboardView')

    def test_overseerstatsview_class(self):
        assert hasattr(library_cog, 'OverseerStatsView')

    def test_overseersearchselectview_class(self):
        assert hasattr(library_cog, 'OverseerSearchSelectView')

    def test_interactiveoverseersearchview_class(self):
        assert hasattr(library_cog, 'InteractiveOverseerSearchView')

    def test_overseersearchmodal_class(self):
        assert hasattr(library_cog, 'OverseerSearchModal')


SEED_DATA = [
    (1, 'game-one',   1, 'Villager',   1, 'Alice',   100, 'Asfro', 691, 0, 1, 0),
    (1, 'game-one',   2, 'Wolf',       2, 'Bob',     101, 'Asfro', 691, 1, 1, 0),
    (1, 'game-one',   3, 'Seer',       1, 'Charlie', 102, 'Asfro', 691, 0, 1, 0),
    (1, 'game-one',   4, 'Doctor',     1, 'Diana',   103, 'Asfro', 691, 0, 1, 0),
    (1, 'game-one',   5, 'Mason',      1, 'Eve',     104, 'Asfro', 691, 0, 1, 0),
    (2, 'game-two',   1, 'Villager',   1, 'Alice',   100, 'Asfro', 691, 1, 1, 0),
    (2, 'game-two',   2, 'Wolf',       2, 'Bob',     101, 'Asfro', 691, 1, 1, 0),
    (2, 'game-two',   3, 'Cult',       4, 'Frank',   105, 'Asfro', 691, 0, 1, 0),
    (3, 'game-three', 1, 'Villager',   1, 'Grace',   106, 'Gear',  365, 1, 1, 0),
    (3, 'game-three', 2, 'Wolf',       2, 'Hank',    107, 'Gear',  365, 0, 1, 0),
    (3, 'game-three', 3, 'Arsonist',   3, 'Ivy',     108, 'Gear',  365, 1, 1, 0),
    (4, 'game-four',  1, 'Villager',   1, 'Alice',   100, 'Asfro', 691, 0, 1, 0),
    (4, 'game-four',  2, 'Wolf',       2, 'Bob',     101, 'Asfro', 691, 0, 1, 0),
    (4, 'game-four',  3, 'Jester',     4, 'Jack',    109, 'Asfro', 691, 1, 1, 0),
    (5, 'game-five',  1, 'Villager',   1, 'Kate',    110, 'Asfro', 691, 0, 1, 0),
    (5, 'game-five',  2, 'Wolf',       2, 'Leo',     111, 'Asfro', 691, 1, 1, 0),
    (5, 'game-five',  3, 'SK',         3, 'Mike',    112, 'Asfro', 691, 1, 1, 0),
]

COLUMNS = "game_number, game_name, role_id, role_name, team, player_name, player_id, sponsor_name, sponsor_id, win, count, mvp"
PLACEHOLDERS = ",".join(["?"] * 12)

HOST_COLUMNS = "game_number, host_name, host_id, count"
HOST_DATA = [
    (1, "Asfro", 691, 1),
    (2, "Asfro", 691, 1),
    (3, "Gear", 365, 1),
    (4, "Asfro", 691, 1),
    (5, "Asfro", 691, 1),
]


def seed_db(db_path):
    """Seed a database with test data and return a LibraryDatabase instance."""
    db = library_cog.LibraryDatabase(db_path)
    conn = sqlite3.connect(db_path)
    conn.executemany(f"INSERT INTO roles ({COLUMNS}) VALUES ({PLACEHOLDERS})", SEED_DATA)
    conn.executemany(f"INSERT INTO game_hosts ({HOST_COLUMNS}) VALUES ({','.join(['?'] * 4)})", HOST_DATA)
    conn.commit()
    conn.close()
    return db


class TestLibraryDatabaseOverseer:
    """Test overseer-related database methods with an in-memory SQLite DB."""

    @pytest.fixture(autouse=True)
    def setup_db(self, tmp_path):
        db_path = os.path.join(tmp_path, "test_overseer.db")
        self.db = seed_db(db_path)

    def test_search_games_by_sponsor_name(self):
        games = self.db.search_games_by_sponsor_name("Asfro")
        game_nums = [g[0] for g in games]
        assert 1 in game_nums and 2 in game_nums and 4 in game_nums and 5 in game_nums
        assert 3 not in game_nums
        assert len(games) == 4

    def test_search_games_by_sponsor_name_case_insensitive(self):
        games = self.db.search_games_by_sponsor_name("asfro")
        assert len(games) == 4

    def test_search_games_by_sponsor_name_no_results(self):
        games = self.db.search_games_by_sponsor_name("Unknown")
        assert len(games) == 0

    def test_get_overseer_stats_teams(self):
        stats = self.db.get_overseer_stats("Asfro")
        assert stats["total_games"] == 4
        ts = stats["team_stats"]
        assert ts["Village"]["wins"] == 1
        assert ts["Village"]["games"] == 4
        assert ts["Village"]["winrate"] == 25.0
        assert ts["Evil"]["wins"] == 3
        assert ts["Evil"]["games"] == 4
        assert ts["Evil"]["winrate"] == 75.0
        assert ts["Random Killer"]["wins"] == 1
        assert ts["Random Killer"]["games"] == 1
        assert ts["Random Killer"]["winrate"] == 100.0
        assert ts["Neutral"]["wins"] == 1
        assert ts["Neutral"]["games"] == 2

    def test_get_overseer_game_history_count(self):
        history = self.db.get_overseer_game_history("Asfro")
        assert len(history) == 4

    def test_get_overseer_game_history_teams(self):
        history = self.db.get_overseer_game_history("Asfro")
        by_num = {g["game_number"]: g for g in history}
        assert by_num[1]["team_counts"][1] == 4
        assert by_num[1]["team_counts"][2] == 1
        assert by_num[1]["winning_teams"] == [2]
        assert sorted(by_num[2]["winning_teams"]) == [1, 2]
        assert by_num[4]["winning_teams"] == [4]

    def test_get_overseer_game_history_sorted(self):
        history = self.db.get_overseer_game_history("Asfro")
        nums = [g["game_number"] for g in history]
        assert nums == sorted(nums, reverse=True)

    def test_get_all_overseer_stats(self):
        all_stats = self.db.get_all_overseer_stats(min_games=1)
        names = {s["sponsor_name"] for s in all_stats}
        assert "Asfro" in names
        assert "Gear" in names

    def test_get_all_overseer_stats_asfro(self):
        all_stats = self.db.get_all_overseer_stats(min_games=1)
        asfro = next(s for s in all_stats if s["sponsor_name"] == "Asfro")
        assert asfro["total_games"] == 4
        assert asfro["village_wins"] == 1
        assert asfro["village_wr"] == 25.0
        assert asfro["evil_wins"] == 3
        assert asfro["evil_wr"] == 75.0

    def test_get_all_overseer_stats_gear(self):
        all_stats = self.db.get_all_overseer_stats(min_games=1)
        gear = next(s for s in all_stats if s["sponsor_name"] == "Gear")
        assert gear["total_games"] == 1
        assert gear["village_wins"] == 1
        assert gear["rk_wins"] == 1

    def test_get_all_overseer_stats_min_games_filter(self):
        all_stats = self.db.get_all_overseer_stats(min_games=3)
        names = [s["sponsor_name"] for s in all_stats]
        assert "Asfro" in names
        assert "Gear" not in names

    def test_no_data_returns_empty(self):
        assert self.db.get_overseer_stats("Nobody") == {}
        assert self.db.get_overseer_game_history("Nobody") == []

    def test_overseer_game_history_team_counts_all_present(self):
        history = self.db.get_overseer_game_history("Gear")
        assert len(history) == 1
        g = history[0]
        assert g["game_number"] == 3
        assert g["team_counts"][1] == 1
        assert g["team_counts"][2] == 1
        assert g["team_counts"][3] == 1
        assert sorted(g["winning_teams"]) == [1, 3]

    def test_player_game_history_descending_order(self):
        """View Game History button should show newest games first."""
        history = self.db.get_player_game_history(100)
        nums = [g["game_number"] for g in history]
        assert nums == [4, 2, 1]

    def test_player_game_history_fields(self):
        history = self.db.get_player_game_history(100)
        assert history[0]["game_name"] == "game-four"
        assert history[0]["team"] == 1
        assert history[0]["mvp"] is False
