"""Tests for Infos cog (auto-generated by testing framework)."""

import pytest
from unittest.mock import MagicMock, AsyncMock, patch
import discord

from cogs import infos_cog


class TestInfos:
    """Validate all commands exist and have required metadata."""

    def test_info_exists(self):
        """Verify info command exists on the cog."""
        assert hasattr(infos_cog.Infos, 'info')

    def test_info_has_help(self):
        """Verify info command has help text."""
        method = getattr(infos_cog.Infos, 'info')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0
