"""Tests for Help Misc cog (auto-generated by testing framework)."""

import pytest
from unittest.mock import MagicMock, AsyncMock, patch
import discord
from discord.ext import commands

from cogs import help_misc_cog


class TestOther:
    """Validate all commands exist and have required metadata."""

    def test_who_exists(self):
        """Verify who command exists on the cog."""
        assert hasattr(help_misc_cog.Other, 'who')

    def test_who_has_help(self):
        """Verify who command has help text."""
        method = getattr(help_misc_cog.Other, 'who')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_where_exists(self):
        """Verify where command exists on the cog."""
        assert hasattr(help_misc_cog.Other, 'where')

    def test_where_has_help(self):
        """Verify where command has help text."""
        method = getattr(help_misc_cog.Other, 'where')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_loc_exists(self):
        """Verify loc command exists on the cog."""
        assert hasattr(help_misc_cog.Other, 'loc')

    def test_loc_has_help(self):
        """Verify loc command has help text."""
        method = getattr(help_misc_cog.Other, 'loc')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_timer_exists(self):
        """Verify timer command exists on the cog."""
        assert hasattr(help_misc_cog.Other, 'timer')

    def test_timer_has_help(self):
        """Verify timer command has help text."""
        method = getattr(help_misc_cog.Other, 'timer')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_roll_exists(self):
        """Verify roll command exists on the cog."""
        assert hasattr(help_misc_cog.Other, 'roll')

    def test_roll_has_help(self):
        """Verify roll command has help text."""
        method = getattr(help_misc_cog.Other, 'roll')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_narrate_exists(self):
        """Verify narrate command exists on the cog."""
        assert hasattr(help_misc_cog.Other, 'narrate')

    def test_narrate_has_help(self):
        """Verify narrate command has help text."""
        method = getattr(help_misc_cog.Other, 'narrate')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_narration_exists(self):
        """Verify narration command exists on the cog."""
        assert hasattr(help_misc_cog.Other, 'narration')

    def test_narration_has_help(self):
        """Verify narration command has help text."""
        method = getattr(help_misc_cog.Other, 'narration')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_anarration_exists(self):
        """Verify anarration command exists on the cog."""
        assert hasattr(help_misc_cog.Other, 'anarration')

    def test_anarration_has_help(self):
        """Verify anarration command has help text."""
        method = getattr(help_misc_cog.Other, 'anarration')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_narrationcolor_exists(self):
        """Verify narrationcolor command exists on the cog."""
        assert hasattr(help_misc_cog.Other, 'narrationcolor')

    def test_narrationcolor_has_help(self):
        """Verify narrationcolor command has help text."""
        method = getattr(help_misc_cog.Other, 'narrationcolor')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_revive_exists(self):
        """Verify revive command exists on the cog."""
        assert hasattr(help_misc_cog.Other, 'revive')

    def test_revive_has_help(self):
        """Verify revive command has help text."""
        method = getattr(help_misc_cog.Other, 'revive')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_deletechannel_exists(self):
        """Verify deletechannel command exists on the cog."""
        assert hasattr(help_misc_cog.Other, 'deletechannel')

    def test_deletechannel_has_help(self):
        """Verify deletechannel command has help text."""
        method = getattr(help_misc_cog.Other, 'deletechannel')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_deletecategory_exists(self):
        """Verify deletecategory command exists on the cog."""
        assert hasattr(help_misc_cog.Other, 'deletecategory')

    def test_deletecategory_has_help(self):
        """Verify deletecategory command has help text."""
        method = getattr(help_misc_cog.Other, 'deletecategory')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_timestamp_exists(self):
        """Verify timestamp command exists on the cog."""
        assert hasattr(help_misc_cog.Other, 'timestamp')

    def test_timestamp_has_help(self):
        """Verify timestamp command has help text."""
        method = getattr(help_misc_cog.Other, 'timestamp')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_time_exists(self):
        """Verify time command exists on the cog."""
        assert hasattr(help_misc_cog.Other, 'time')

    def test_time_has_help(self):
        """Verify time command has help text."""
        method = getattr(help_misc_cog.Other, 'time')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_gettag_exists(self):
        """Verify gettag command exists on the cog."""
        assert hasattr(help_misc_cog.Other, 'gettag')

    def test_gettag_has_help(self):
        """Verify gettag command has help text."""
        method = getattr(help_misc_cog.Other, 'gettag')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_firstpin_exists(self):
        """Verify firstpin command exists on the cog."""
        assert hasattr(help_misc_cog.Other, 'firstpin')

    def test_firstpin_has_help(self):
        """Verify firstpin command has help text."""
        method = getattr(help_misc_cog.Other, 'firstpin')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_ping_exists(self):
        """Verify ping command exists on the cog."""
        assert hasattr(help_misc_cog.Other, 'ping')

    def test_ping_has_help(self):
        """Verify ping command has help text."""
        method = getattr(help_misc_cog.Other, 'ping')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_ding_exists(self):
        """Verify ding command exists on the cog."""
        assert hasattr(help_misc_cog.Other, 'ding')

    def test_ding_has_help(self):
        """Verify ding command has help text."""
        method = getattr(help_misc_cog.Other, 'ding')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_dice_exists(self):
        """Verify dice command exists on the cog."""
        assert hasattr(help_misc_cog.Other, 'dice')

    def test_dice_has_help(self):
        """Verify dice command has help text."""
        method = getattr(help_misc_cog.Other, 'dice')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_goat_exists(self):
        """Verify goat command exists on the cog."""
        assert hasattr(help_misc_cog.Other, 'goat')

    def test_goat_has_help(self):
        """Verify goat command has help text."""
        method = getattr(help_misc_cog.Other, 'goat')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_help2_exists(self):
        """Verify help2 command exists on the cog."""
        assert hasattr(help_misc_cog.Other, 'help2')

    def test_help2_has_help(self):
        """Verify help2 command has help text."""
        method = getattr(help_misc_cog.Other, 'help2')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_searchhelp_exists(self):
        """Verify searchhelp command exists on the cog."""
        assert hasattr(help_misc_cog.Other, 'searchhelp')

    def test_searchhelp_has_help(self):
        """Verify searchhelp command has help text."""
        method = getattr(help_misc_cog.Other, 'searchhelp')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_help_exists(self):
        """Verify help command exists on the cog."""
        assert hasattr(help_misc_cog.Other, 'help')

    def test_help_has_help(self):
        """Verify help command has help text."""
        method = getattr(help_misc_cog.Other, 'help')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_timezoneselectview_instantiates(self):
        """Verify TimezoneSelectView view can be instantiated."""
        # TimezoneSelectView — requires cog/bot context to instantiate
        pass

    def test_confirmdeleteview_instantiates(self):
        """Verify ConfirmDeleteView view can be instantiated."""
        # ConfirmDeleteView — requires cog/bot context to instantiate
        pass

    def test_narrationcolorview_instantiates(self):
        """Verify NarrationColorView view can be instantiated."""
        # NarrationColorView — requires cog/bot context to instantiate
        pass

    def test_reviveview_instantiates(self):
        """Verify ReviveView view can be instantiated."""
        # ReviveView — requires cog/bot context to instantiate
        pass


# ── Deep tests for narration auto-pin ────────────────────────────────────────

import asyncio
from unittest.mock import AsyncMock, MagicMock, patch


def _run(coro):
    loop = asyncio.new_event_loop()
    try:
        return loop.run_until_complete(coro)
    finally:
        loop.close()


class TestNarrationAutoPin:
    """Tests for narration _send_narration auto-pin behavior."""

    def test_send_narration_pins_first_message(self):
        """Verify _send_narration pins the first sent message."""
        cog = help_misc_cog.Other(None)
        ctx = MagicMock()
        ctx.guild = MagicMock()
        ctx.guild.id = 100
        ctx.guild.roles = []
        ctx.guild.channels = []
        ctx.channel = MagicMock()
        ctx.channel.name = "test-channel"
        ctx.author = MagicMock()
        ctx.author.display_name = "Admin"
        ctx.author.display_avatar = MagicMock()
        ctx.author.display_avatar.url = "http://example.com/avatar.png"
        ctx.message = MagicMock()
        ctx.message.content = ".n Test narration"
        ctx.message.delete = AsyncMock()
        ctx.prefix = "."
        ctx.invoked_with = "n"

        sent_msg = MagicMock()
        sent_msg.pin = AsyncMock()
        ctx.send = AsyncMock(return_value=sent_msg)

        with patch('cogs.help_misc_cog.load_guild_data', return_value={
            "alive_role_name": "Alive",
            "sponsor_role_name": "Sponsor",
            "narration_color": 0xdc143c,
            "narration_log_channel_name": "commentary",
        }):
            with patch('discord.utils.get', return_value=None):
                _run(cog._send_narration(ctx, "Test narration", ping_roles=False))

        sent_msg.pin.assert_called_once()

    def test_send_narration_handles_pin_failure(self):
        """Verify _send_narration gracefully handles pin failure."""
        cog = help_misc_cog.Other(None)
        ctx = MagicMock()
        ctx.guild = MagicMock()
        ctx.guild.id = 100
        ctx.guild.roles = []
        ctx.guild.channels = []
        ctx.channel = MagicMock()
        ctx.channel.name = "test-channel"
        ctx.author = MagicMock()
        ctx.author.display_name = "Admin"
        ctx.author.display_avatar = MagicMock()
        ctx.author.display_avatar.url = "http://example.com/avatar.png"
        ctx.message = MagicMock()
        ctx.message.content = ".n Test"
        ctx.message.delete = AsyncMock()
        ctx.prefix = "."
        ctx.invoked_with = "n"

        sent_msg = MagicMock()
        sent_msg.pin = AsyncMock(side_effect=discord.errors.Forbidden(MagicMock(), MagicMock()))
        ctx.send = AsyncMock(return_value=sent_msg)

        with patch('cogs.help_misc_cog.load_guild_data', return_value={
            "alive_role_name": "Alive",
            "sponsor_role_name": "Sponsor",
            "narration_color": 0xdc143c,
            "narration_log_channel_name": "commentary",
        }):
            with patch('discord.utils.get', return_value=None):
                _run(cog._send_narration(ctx, "Test", ping_roles=False))

        sent_msg.pin.assert_called_once()

    def test_send_narration_stores_sent_messages(self):
        """Verify _send_narration tracks sent messages in a list."""
        cog = help_misc_cog.Other(None)
        ctx = MagicMock()
        ctx.guild = MagicMock()
        ctx.guild.id = 100
        ctx.guild.roles = []
        ctx.guild.channels = []
        ctx.channel = MagicMock()
        ctx.channel.name = "test-channel"
        ctx.author = MagicMock()
        ctx.author.display_name = "Admin"
        ctx.author.display_avatar = MagicMock()
        ctx.author.display_avatar.url = "http://example.com/avatar.png"
        ctx.message = MagicMock()
        ctx.message.content = ".n Test"
        ctx.message.delete = AsyncMock()
        ctx.prefix = "."
        ctx.invoked_with = "n"

        msg1 = MagicMock()
        msg1.pin = AsyncMock()
        msg2 = MagicMock()
        msg2.pin = AsyncMock()
        ctx.send = AsyncMock(side_effect=[msg1, msg2])

        long_text = "x" * 5000
        with patch('cogs.help_misc_cog.load_guild_data', return_value={
            "alive_role_name": "Alive",
            "sponsor_role_name": "Sponsor",
            "narration_color": 0xdc143c,
            "narration_log_channel_name": "commentary",
        }):
            with patch('discord.utils.get', return_value=None):
                _run(cog._send_narration(ctx, long_text, ping_roles=False))

        assert ctx.send.call_count == 2
        msg1.pin.assert_called_once()
        msg2.pin.assert_not_called()


class FakeHistory:
    """Async iterator over a list of messages (for channel.history)."""

    def __init__(self, messages):
        self._messages = messages
        self._it = None

    def __aiter__(self):
        self._it = iter(self._messages)
        return self

    async def __anext__(self):
        try:
            return next(self._it)
        except StopIteration:
            raise StopAsyncIteration


def make_msg(content="hello", author_id=123456, jump_url="https://discord.com/channels/a"):
    msg = MagicMock()
    msg.content = content
    msg.author.id = author_id
    msg.jump_url = jump_url
    return msg


class TestFirstMsg:
    def test_firstmsg_exists(self):
        """Verify firstmsg command exists on the cog."""
        assert hasattr(help_misc_cog.Other, 'firstmsg')

    def test_firstmsg_has_help(self):
        """Verify firstmsg command has help text."""
        method = getattr(help_misc_cog.Other, 'firstmsg')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    @pytest.mark.asyncio
    async def test_no_channel_uses_current(self):
        cog = help_misc_cog.Other(MagicMock())
        author = MagicMock()
        author.guild_permissions.administrator = False
        channel = MagicMock()
        channel.history.return_value = FakeHistory([make_msg("First ever message")])
        ctx = MagicMock()
        ctx.author = author
        ctx.channel = channel
        ctx.send = AsyncMock()
        await cog.firstmsg.callback(cog, ctx)
        channel.history.assert_called_once_with(limit=1, oldest_first=True)
        ctx.send.assert_awaited_once()
        embed = ctx.send.await_args.kwargs["embed"]
        assert isinstance(embed, discord.Embed)
        assert "First ever message" in embed.description
        assert any("123456" in f.value for f in embed.fields)

    @pytest.mark.asyncio
    async def test_with_channel_as_admin(self):
        cog = help_misc_cog.Other(MagicMock())
        author = MagicMock()
        author.guild_permissions.administrator = True
        target = MagicMock()
        target.history.return_value = FakeHistory([make_msg("From target channel")])
        ctx = MagicMock()
        ctx.author = author
        ctx.channel = MagicMock()
        ctx.send = AsyncMock()
        await cog.firstmsg.callback(cog, ctx, target)
        target.history.assert_called_once_with(limit=1, oldest_first=True)
        ctx.send.assert_awaited_once()

    @pytest.mark.asyncio
    async def test_with_channel_non_admin_denied(self):
        cog = help_misc_cog.Other(MagicMock())
        author = MagicMock()
        author.guild_permissions.administrator = False
        target = MagicMock()
        ctx = MagicMock()
        ctx.author = author
        ctx.send = AsyncMock()
        await cog.firstmsg.callback(cog, ctx, target)
        ctx.send.assert_awaited_once()
        assert "admin" in ctx.send.await_args[0][0].lower()
        target.history.assert_not_called()

    @pytest.mark.asyncio
    async def test_empty_channel(self):
        cog = help_misc_cog.Other(MagicMock())
        author = MagicMock()
        author.guild_permissions.administrator = True
        channel = MagicMock()
        channel.history.return_value = FakeHistory([])
        ctx = MagicMock()
        ctx.author = author
        ctx.channel = channel
        ctx.send = AsyncMock()
        await cog.firstmsg.callback(cog, ctx)
        ctx.send.assert_awaited_once()
        assert "No messages" in ctx.send.await_args[0][0]


class TestCommandAutocorrect:
    """Tests for the misspelled-command suggestion feature."""

    @staticmethod
    def _make_command(name, aliases=(), qualified_name=None):
        cmd = MagicMock()
        cmd.name = name
        cmd.aliases = aliases
        cmd.qualified_name = qualified_name or name
        return cmd

    def _make_cog(self, commands):
        bot = MagicMock()
        bot.walk_commands.return_value = commands
        return help_misc_cog.Other(bot)

    def test_suggest_corrects_misspelling(self):
        cog = self._make_cog([
            self._make_command("calendar"),
            self._make_command("role"),
            self._make_command("vote"),
        ])
        assert cog._suggest_commands("calender") == ["calendar"]

    def test_suggest_matches_alias(self):
        cog = self._make_cog([
            self._make_command("pendingknock", aliases=["knocks"]),
        ])
        assert cog._suggest_commands("knok") == ["pendingknock"]

    def test_suggest_empty_for_unrelated_word(self):
        cog = self._make_cog([
            self._make_command("calendar"),
            self._make_command("role"),
        ])
        assert cog._suggest_commands("xyzzy") == []

    def test_suggest_requires_first_letter_for_short_words(self):
        cog = self._make_cog([
            self._make_command("add"),
            self._make_command("role"),
        ])
        assert cog._suggest_commands("alt") == []

    @pytest.mark.asyncio
    async def test_listener_sends_suggestion(self):
        cog = self._make_cog([
            self._make_command("calendar"),
            self._make_command("role"),
        ])
        ctx = MagicMock()
        ctx.author.bot = False
        ctx.invoked_with = "calender"
        ctx.prefix = "."
        ctx.send = AsyncMock()
        error = commands.CommandNotFound("Command \"calender\" is not found")
        await cog.on_command_error(ctx, error)
        ctx.send.assert_awaited_once()
        assert "calendar" in ctx.send.await_args[0][0]

    @pytest.mark.asyncio
    async def test_listener_ignores_other_errors(self):
        cog = self._make_cog([self._make_command("calendar")])
        ctx = MagicMock()
        ctx.author.bot = False
        ctx.invoked_with = "calender"
        ctx.send = AsyncMock()
        error = ValueError("boom")
        await cog.on_command_error(ctx, error)
        ctx.send.assert_not_called()
