"""Tests for Channel cog (auto-generated by testing framework)."""

import pytest
from unittest.mock import MagicMock, AsyncMock, patch
import discord

from cogs import channel_cog


class TestChannelMap:
    """Validate all commands exist and have required metadata."""

    def test_cmd_channels_exists(self):
        """Verify cmd_channels command exists on the cog."""
        assert hasattr(channel_cog.ChannelMap, 'cmd_channels')

    def test_cmd_channels_has_help(self):
        """Verify cmd_channels command has help text."""
        method = getattr(channel_cog.ChannelMap, 'cmd_channels')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_cmd_publicmap_exists(self):
        """Verify cmd_publicmap command exists on the cog."""
        assert hasattr(channel_cog.ChannelMap, 'cmd_publicmap')

    def test_cmd_publicmap_has_help(self):
        """Verify cmd_publicmap command has help text."""
        method = getattr(channel_cog.ChannelMap, 'cmd_publicmap')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_cmd_privatemap_exists(self):
        """Verify cmd_privatemap command exists on the cog."""
        assert hasattr(channel_cog.ChannelMap, 'cmd_privatemap')

    def test_cmd_privatemap_has_help(self):
        """Verify cmd_privatemap command has help text."""
        method = getattr(channel_cog.ChannelMap, 'cmd_privatemap')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0
