"""Tests for Analytics cog (auto-generated by testing framework)."""

from datetime import datetime, timedelta

import pytest
from unittest.mock import MagicMock, AsyncMock, patch
import discord

from cogs import analytics_cog


class TestAnalyticsCog:
    """Validate all commands exist and have required metadata."""

    def test_analytics_exists(self):
        """Verify analytics command exists on the cog."""
        assert hasattr(analytics_cog.AnalyticsCog, 'analytics')

    def test_analytics_has_help(self):
        """Verify analytics command has help text."""
        method = getattr(analytics_cog.AnalyticsCog, 'analytics')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_analytics_aliases(self):
        """Verify analytics command has astats alias."""
        method = getattr(analytics_cog.AnalyticsCog, 'analytics')
        aliases = getattr(method, 'aliases', [])
        assert 'astats' in aliases

    def test_failures_exists(self):
        """Verify failures command exists on the cog."""
        assert hasattr(analytics_cog.AnalyticsCog, 'failures')

    def test_failures_has_help(self):
        """Verify failures command has help text."""
        method = getattr(analytics_cog.AnalyticsCog, 'failures')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_analyticsview_instantiates(self):
        """Verify AnalyticsView can be instantiated."""
        pass

    def test_analyticsview_build_summary(self):
        """Verify AnalyticsView._build_summary exists."""
        assert hasattr(analytics_cog.AnalyticsView, '_build_summary')

    def test_analyticsview_build_recent_errors(self):
        """Verify AnalyticsView._build_recent_errors exists."""
        assert hasattr(analytics_cog.AnalyticsView, '_build_recent_errors')

    def test_analyticsview_build_commands(self):
        """Verify AnalyticsView._build_commands exists."""
        assert hasattr(analytics_cog.AnalyticsView, '_build_commands')

    def test_analyticsview_build_health(self):
        """Verify AnalyticsView._build_health exists."""
        assert hasattr(analytics_cog.AnalyticsView, '_build_health')

    def test_analyticsview_select_exists(self):
        """Verify AnalyticsView has a page_select dropdown."""
        assert hasattr(analytics_cog.AnalyticsView, 'page_select')

    def test_command_filter_modal(self):
        """Verify CommandFilterModal class exists."""
        assert hasattr(analytics_cog, 'CommandFilterModal')

    def test_error_filter_modal(self):
        """Verify ErrorFilterModal class exists."""
        assert hasattr(analytics_cog, 'ErrorFilterModal')

    def test_full_traceback_modal(self):
        """Verify FullTracebackModal class exists."""
        assert hasattr(analytics_cog, 'FullTracebackModal')

    def test_traceback_lookup_modal(self):
        """Verify TracebackLookupModal class exists."""
        assert hasattr(analytics_cog, 'TracebackLookupModal')

    def test_reset_button_exists(self):
        """Verify reset_errors button exists on AnalyticsView."""
        assert hasattr(analytics_cog.AnalyticsView, 'reset_errors')

    def test_errorpaginationview_instantiates(self):
        """Verify ErrorPaginationView can be instantiated."""
        pass

    def test_dev_only_check(self):
        """Verify _dev_only returns a check."""
        check = analytics_cog._dev_only()
        assert callable(check)


class TestExtractErrorMessage:
    """Tests for _extract_error_message helper."""

    def test_extract_standard(self):
        msg = analytics_cog._extract_error_message(
            "ValueError: something broke", "ValueError"
        )
        assert msg == "something broke"

    def test_extract_with_traceback(self):
        tb = (
            'Traceback (most recent call last):\n'
            '  File "foo.py", line 10, in bar\n'
            '    baz()\n'
            'KeyError: \'missing_key\''
        )
        msg = analytics_cog._extract_error_message(tb, "KeyError")
        assert msg == "'missing_key'"

    def test_extract_no_message(self):
        msg = analytics_cog._extract_error_message("ValueError", "ValueError")
        assert msg == "ValueError"

    def test_extract_empty_tb(self):
        msg = analytics_cog._extract_error_message("", "TypeError")
        assert msg == "TypeError"

    def test_extract_no_tb(self):
        msg = analytics_cog._extract_error_message(None, "TypeError")
        assert msg == "TypeError"

    def test_extract_last_line_without_exc_type(self):
        tb = 'Traceback (most recent call last):\n  File "x.py", line 1, in f\n    raise\nRuntimeError: boom'
        msg = analytics_cog._extract_error_message(tb, "RuntimeError")
        assert msg == "boom"


class TestErrorDetailView:
    """Test the error detail page builder exists."""

    def test_build_error_detail_exists(self):
        assert hasattr(analytics_cog.AnalyticsView, '_build_error_detail')

    def test_error_select_exists(self):
        assert hasattr(analytics_cog.AnalyticsView, 'error_select')


class TestHumanTimestamp:
    """Tests for _human_timestamp helper (deterministic, time-independent)."""

    FIXED_NOW = datetime(2026, 7, 8, 14, 30, 0)  # Jul 8, 2:30 PM UTC

    def _call(self, delta):
        ts = (self.FIXED_NOW + delta).isoformat()
        return analytics_cog._human_timestamp(ts, _now=self.FIXED_NOW)

    def test_just_now(self):
        result = self._call(timedelta())
        assert result == "just now"

    def test_minutes_ago(self):
        result = self._call(timedelta(minutes=-5))
        assert result == "5 min ago"

    def test_hours_ago_same_day(self):
        """3 hours ago on the same day → 'Today' format."""
        result = self._call(timedelta(hours=-3))
        assert result.startswith("Today")

    def test_crosses_day(self):
        """30 hours ago → 'Yesterday'."""
        result = self._call(timedelta(hours=-30))
        assert result.startswith("Yesterday")

    def test_none_input(self):
        assert analytics_cog._human_timestamp(None) == "?"

    def test_empty_input(self):
        assert analytics_cog._human_timestamp("") == "?"

    def test_today_format(self):
        """2 hours ago on the same day → 'Today'."""
        result = self._call(timedelta(hours=-2))
        assert result.startswith("Today")

    def test_yesterday_format(self):
        """26 hours ago → 'Yesterday'."""
        result = self._call(timedelta(hours=-26))
        assert result.startswith("Yesterday")

    def test_older_format(self):
        """5 days ago → absolute date, no 'ago'/'Today'/'Yesterday'."""
        result = self._call(timedelta(days=-5))
        assert "ago" not in result
        assert "Today" not in result
        assert "Yesterday" not in result


class TestGetMemoryStr:
    """Test the memory helper exists."""

    def test_get_memory_str_exists(self):
        assert callable(analytics_cog._get_memory_str)

    def test_get_memory_str_returns_string(self):
        result = analytics_cog._get_memory_str()
        assert isinstance(result, str)
        assert len(result) > 0
