"""Tests for Presets cog (auto-generated by testing framework)."""

import pytest
from unittest.mock import MagicMock, AsyncMock, patch
import discord

from cogs import presets_cog


class TestPresets:
    """Validate all commands exist and have required metadata."""

    def test_preset_exists(self):
        """Verify preset command exists on the cog."""
        assert hasattr(presets_cog.Presets, 'preset')

    def test_preset_has_help(self):
        """Verify preset command has help text."""
        method = getattr(presets_cog.Presets, 'preset')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_ospreset_exists(self):
        """Verify ospreset command exists on the cog."""
        assert hasattr(presets_cog.Presets, 'ospreset')

    def test_ospreset_has_help(self):
        """Verify ospreset command has help text."""
        method = getattr(presets_cog.Presets, 'ospreset')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_ospresetsort_exists(self):
        """Verify ospresetsort command exists on the cog."""
        assert hasattr(presets_cog.Presets, 'ospresetsort')

    def test_ospresetsort_has_help(self):
        """Verify ospresetsort command has help text."""
        method = getattr(presets_cog.Presets, 'ospresetsort')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_ospresetcategories_exists(self):
        """Verify ospresetcategories command exists on the cog."""
        assert hasattr(presets_cog.Presets, 'ospresetcategories')

    def test_ospresetcategories_has_help(self):
        """Verify ospresetcategories command has help text."""
        method = getattr(presets_cog.Presets, 'ospresetcategories')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_resolve_category_display_with_none(self):
        """Verify resolve_category_display handles None correctly."""
        assert presets_cog.resolve_category_display(None) == "Uncategorized"

    def test_resolve_category_display_with_custom_category(self):
        """Verify resolve_category_display returns custom category if it exists."""
        custom_cats = ["CustomPower"]
        presets_cog.CATEGORY_DISPLAY["CustomPower"] = "CustomPower (custom)"
        try:
            result = presets_cog.resolve_category_display("CustomPower", custom_cats)
            assert result == "CustomPower (custom)"
        finally:
            presets_cog.CATEGORY_DISPLAY.pop("CustomPower", None)

    def test_resolve_category_display_with_uncategorized_custom(self):
        """Verify resolve_category_display returns custom category not in default display."""
        custom_cats = ["CustomPower"]
        assert presets_cog.resolve_category_display("CustomPower", custom_cats) == "CustomPower"

    def test_get_custom_categories_default(self):
        """Verify _get_custom_categories returns empty list by default."""
        cog = presets_cog.Presets(None)
        with patch('cogs.presets_cog.load_guild_data', return_value={}):
            result = cog._get_custom_categories("123")
            assert result == []

    def test_set_custom_categories(self):
        """Verify _set_custom_categories saves custom categories."""
        cog = presets_cog.Presets(None)
        mock_save = MagicMock()
        with patch('cogs.presets_cog.load_guild_data', return_value={}):
            with patch('cogs.presets_cog.save_guild_data', mock_save):
                cog._set_custom_categories("123", ["Custom1", "Custom2"])
                assert mock_save.called
                saved_data = mock_save.call_args[0][1]
                assert saved_data.get("preset_custom_categories") == ["Custom1", "Custom2"]

    def test_get_all_categories(self):
        """Verify _get_all_categories merges default and custom categories."""
        cog = presets_cog.Presets(None)
        with patch.object(cog, '_get_custom_categories', return_value=["CustomPower"]):
            result = cog._get_all_categories("123")
            assert "CustomPower" in result
            assert len(result) > len(presets_cog.ABILITY_CATEGORIES)

    def test_ospresetcategories_requires_admin(self):
        """Verify ospresetcategories command requires administrator permission."""
        method = getattr(presets_cog.Presets, 'ospresetcategories')
        checks = getattr(method, 'checks', None)
        assert checks is not None, "Command should have permission checks"


# ── Deep tests for ospreset label truncation fixes ────────────────────────────

import discord


class TestOspresetLabelFixes:
    """Tests for SelectOption label truncation in ospreset swap/remove."""

    def test_select_option_label_max_length_swap(self):
        """Verify swap SelectOption labels never exceed 100 chars."""
        long_info = "A" * 200
        preview = long_info[:80] + ('...' if len(long_info) > 80 else '')
        label = f"1. {preview}"
        assert len(label) <= 100

    def test_select_option_label_max_length_remove(self):
        """Verify remove SelectOption labels never exceed 100 chars."""
        long_info = "B" * 300
        preview = long_info[:80] + ('...' if len(long_info) > 80 else '')
        label = f"10. {preview}"
        assert len(label) <= 100

    def test_select_option_label_short_text(self):
        """Verify short text is not truncated."""
        short_info = "Heal target"
        preview = short_info[:80] + ('...' if len(short_info) > 80 else '')
        assert preview == "Heal target"

    def test_select_option_label_exactly_80_chars(self):
        """Verify text at exactly 80 chars is not truncated."""
        info = "C" * 80
        preview = info[:80] + ('...' if len(info) > 80 else '')
        assert preview == info
        assert not preview.endswith('...')

    def test_select_option_label_81_chars(self):
        """Verify text at 81 chars is truncated."""
        info = "D" * 81
        preview = info[:80] + ('...' if len(info) > 80 else '')
        assert preview.endswith('...')
        assert len(preview) == 83

    def test_swap_max_values_adapts_to_preset_count(self):
        """Verify swap max_values is min(2, len(options))."""
        for count in [1, 2, 3, 5]:
            options = [f"opt{i}" for i in range(count)]
            max_vals = min(2, len(options))
            assert max_vals == min(2, count)

    def test_select_options_capped_at_25(self):
        """Verify options list is sliced to max 25 for Discord Select limit."""
        options = list(range(30))
        capped = options[:25]
        assert len(capped) == 25
