"""Tests for Data Utils cog (auto-generated by testing framework)."""

import pytest
from unittest.mock import MagicMock, AsyncMock, patch
import discord

from cogs import data_utils


class TestDataUtilsCommands:
    """Validate all commands exist and have required metadata."""
