"""Tests for Home cog (auto-generated by testing framework)."""

import pytest
from unittest.mock import MagicMock, AsyncMock, patch
import discord

from cogs import home_cog


class TestHome:
    """Validate all commands exist and have required metadata."""

    def test_home_exists(self):
        """Verify home command exists on the cog."""
        assert hasattr(home_cog.Home, 'home')

    def test_home_has_help(self):
        """Verify home command has help text."""
        method = getattr(home_cog.Home, 'home')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_rolechat_exists(self):
        """Verify rolechat command exists on the cog."""
        assert hasattr(home_cog.Home, 'rolechat')

    def test_rolechat_has_help(self):
        """Verify rolechat command has help text."""
        method = getattr(home_cog.Home, 'rolechat')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_owner_exists(self):
        """Verify owner command exists on the cog."""
        assert hasattr(home_cog.Home, 'owner')

    def test_owner_has_help(self):
        """Verify owner command has help text."""
        method = getattr(home_cog.Home, 'owner')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0
