"""Tests for Economy cog (auto-generated by testing framework)."""

import asyncio
import inspect
from types import SimpleNamespace

import pytest
from unittest.mock import MagicMock, AsyncMock, patch
import discord

from cogs import economy_cog
from cogs.data_utils import load_guild_data, save_guild_data


class TestEconomy:
    """Validate all commands exist and have required metadata."""

    def test_balance_exists(self):
        """Verify balance command exists on the cog."""
        assert hasattr(economy_cog.Economy, 'balance')

    def test_balance_has_help(self):
        """Verify balance command has help text."""
        method = getattr(economy_cog.Economy, 'balance')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_collect_exists(self):
        """Verify collect command exists on the cog."""
        assert hasattr(economy_cog.Economy, 'collect')

    def test_collect_has_help(self):
        """Verify collect command has help text."""
        method = getattr(economy_cog.Economy, 'collect')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_setcollect_exists(self):
        """Verify setcollect command exists on the cog."""
        assert hasattr(economy_cog.Economy, 'setcollect')

    def test_setcollect_has_help(self):
        """Verify setcollect command has help text."""
        method = getattr(economy_cog.Economy, 'setcollect')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_shop_exists(self):
        """Verify shop command exists on the cog."""
        assert hasattr(economy_cog.Economy, 'shop')

    def test_shop_has_help(self):
        """Verify shop command has help text."""
        method = getattr(economy_cog.Economy, 'shop')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_buy_exists(self):
        """Verify buy command exists on the cog."""
        assert hasattr(economy_cog.Economy, 'buy')

    def test_buy_has_help(self):
        """Verify buy command has help text."""
        method = getattr(economy_cog.Economy, 'buy')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_inventory_exists(self):
        """Verify inventory command exists on the cog."""
        assert hasattr(economy_cog.Economy, 'inventory')

    def test_inventory_has_help(self):
        """Verify inventory command has help text."""
        method = getattr(economy_cog.Economy, 'inventory')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_give_exists(self):
        """Verify give command exists on the cog."""
        assert hasattr(economy_cog.Economy, 'give')

    def test_give_has_help(self):
        """Verify give command has help text."""
        method = getattr(economy_cog.Economy, 'give')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_additem_exists(self):
        """Verify additem command exists on the cog."""
        assert hasattr(economy_cog.Economy, 'additem')

    def test_additem_has_help(self):
        """Verify additem command has help text."""
        method = getattr(economy_cog.Economy, 'additem')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_edititem_exists(self):
        """Verify edititem command exists on the cog."""
        assert hasattr(economy_cog.Economy, 'edititem')

    def test_edititem_has_help(self):
        """Verify edititem command has help text."""
        method = getattr(economy_cog.Economy, 'edititem')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_delitem_exists(self):
        """Verify delitem command exists on the cog."""
        assert hasattr(economy_cog.Economy, 'delitem')

    def test_delitem_has_help(self):
        """Verify delitem command has help text."""
        method = getattr(economy_cog.Economy, 'delitem')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_reset_economy_exists(self):
        """Verify reset_economy command exists on the cog."""
        assert hasattr(economy_cog.Economy, 'reset_economy')

    def test_reset_economy_has_help(self):
        """Verify reset_economy command has help text."""
        method = getattr(economy_cog.Economy, 'reset_economy')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_clear_inventory_exists(self):
        """Verify clear_inventory command exists on the cog."""
        assert hasattr(economy_cog.Economy, 'clear_inventory')

    def test_clear_inventory_has_help(self):
        """Verify clear_inventory command has help text."""
        method = getattr(economy_cog.Economy, 'clear_inventory')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_addmoney_exists(self):
        """Verify addmoney command exists on the cog."""
        assert hasattr(economy_cog.Economy, 'addmoney')

    def test_addmoney_has_help(self):
        """Verify addmoney command has help text."""
        method = getattr(economy_cog.Economy, 'addmoney')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_removemoney_exists(self):
        """Verify removemoney command exists on the cog."""
        assert hasattr(economy_cog.Economy, 'removemoney')

    def test_removemoney_has_help(self):
        """Verify removemoney command has help text."""
        method = getattr(economy_cog.Economy, 'removemoney')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_give_money_exists(self):
        """Verify give_money command exists on the cog."""
        assert hasattr(economy_cog.Economy, 'give_money')

    def test_give_money_has_help(self):
        """Verify give_money command has help text."""
        method = getattr(economy_cog.Economy, 'give_money')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_sell_item_exists(self):
        """Verify sell_item command exists on the cog."""
        assert hasattr(economy_cog.Economy, 'sell_item')

    def test_sell_item_has_help(self):
        """Verify sell_item command has help text."""
        method = getattr(economy_cog.Economy, 'sell_item')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_add_money_role_exists(self):
        """Verify add_money_role command exists on the cog."""
        assert hasattr(economy_cog.Economy, 'add_money_role')

    def test_add_money_role_has_help(self):
        """Verify add_money_role command has help text."""
        method = getattr(economy_cog.Economy, 'add_money_role')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_leaderboard_exists(self):
        """Verify leaderboard command exists on the cog."""
        assert hasattr(economy_cog.Economy, 'leaderboard')

    def test_leaderboard_has_help(self):
        """Verify leaderboard command has help text."""
        method = getattr(economy_cog.Economy, 'leaderboard')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_use_item_exists(self):
        """Verify use_item command exists on the cog."""
        assert hasattr(economy_cog.Economy, 'use_item')

    def test_use_item_has_help(self):
        """Verify use_item command has help text."""
        method = getattr(economy_cog.Economy, 'use_item')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_additemrole_exists(self):
        """Verify additemrole command exists on the cog."""
        assert hasattr(economy_cog.Economy, 'additemrole')

    def test_additemrole_has_help(self):
        """Verify additemrole command has help text."""
        method = getattr(economy_cog.Economy, 'additemrole')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_removeitem_exists(self):
        """Verify removeitem command exists on the cog."""
        assert hasattr(economy_cog.Economy, 'removeitem')

    def test_removeitem_has_help(self):
        """Verify removeitem command has help text."""
        method = getattr(economy_cog.Economy, 'removeitem')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_confirmview_defined(self):
        """Verify ConfirmView view is defined in the module."""
        assert hasattr(economy_cog, 'ConfirmView')


def _fresh_economy_db(tmp_path, monkeypatch):
    import utils.bot_db as bot_db
    import utils.economy_db as economy_db
    # Point the migration source at a non-existent temp file so the legacy
    # bot.db economy data is never pulled into the temp economy.db during tests.
    monkeypatch.setattr(bot_db, "DB_DIR", str(tmp_path))
    monkeypatch.setattr(bot_db, "DB_PATH", str(tmp_path / "bot.db"))
    monkeypatch.setattr(bot_db, "_DB_READY", False)
    monkeypatch.setattr(bot_db, "_MIGRATION_ATTEMPTED", False)
    monkeypatch.setattr(economy_db, "DB_DIR", str(tmp_path))
    monkeypatch.setattr(economy_db, "DB_PATH", str(tmp_path / "economy.db"))
    monkeypatch.setattr(economy_db, "_DB_READY", False)
    monkeypatch.setattr(economy_db, "_BOT_DB_MIGRATED", False)
    return economy_db


def test_removed_default_item_is_not_reseeded(tmp_path, monkeypatch):
    """Deleting a default shop item must stay deleted even after re-seeding (on .shop / restart)."""
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    guild_id = 999
    name = "🎆 Fireworks"

    economy_db.add_shop_item(guild_id, name=name, description="Reveal", price=100, is_default=True)
    assert economy_db.remove_shop_item_by_name(guild_id, name) is True
    assert economy_db.get_shop_items(guild_id) == []

    cog = economy_cog.Economy(bot=MagicMock())
    guild = SimpleNamespace(id=guild_id)
    asyncio.run(cog._ensure_default_items(guild))
    asyncio.run(cog._ensure_default_items(guild))

    names = [item["name"] for item in economy_db.get_shop_items(guild_id)]
    assert name not in names


def test_removed_default_item_stays_gone_across_restart(tmp_path, monkeypatch):
    """Simulate bot restart: fresh DB connection/state must not resurrect the item."""
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    guild_id = 777
    name = "👟 Shoes"

    economy_db.add_shop_item(guild_id, name=name, description="Extra visit", price=250, is_default=True)
    assert economy_db.remove_shop_item_by_name(guild_id, name) is True

    # Simulate restart: reset in-memory ready flags, reconnect to same file.
    monkeypatch.setattr(economy_db, "_DB_READY", False)
    monkeypatch.setattr(economy_db, "_BOT_DB_MIGRATED", False)

    cog = economy_cog.Economy(bot=MagicMock())
    asyncio.run(cog._ensure_default_items(SimpleNamespace(id=guild_id)))

    names = [item["name"] for item in economy_db.get_shop_items(guild_id)]
    assert name not in names


def test_missing_default_item_is_seeded_when_not_removed(tmp_path, monkeypatch):
    """Existing behavior preserved: unremoved defaults are still auto-seeded."""
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    guild_id = 555

    cog = economy_cog.Economy(bot=MagicMock())
    asyncio.run(cog._ensure_default_items(SimpleNamespace(id=guild_id)))

    names = [item["name"] for item in economy_db.get_shop_items(guild_id)]
    assert "🎆 Fireworks" in names


def test_custom_item_delete_does_not_tombstone_or_reseed(tmp_path, monkeypatch):
    """Deleting a custom (non-default) item must not create a tombstone and must stay gone."""
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    guild_id = 444
    name = "🧿 Custom Talisman"

    economy_db.add_shop_item(guild_id, name=name, description="", price=500, is_default=False)
    assert economy_db.remove_shop_item_by_name(guild_id, name) is True
    assert economy_db.get_shop_items(guild_id) == []
    assert economy_db.get_removed_default_items(guild_id) == set()

    cog = economy_cog.Economy(bot=MagicMock())
    asyncio.run(cog._ensure_default_items(SimpleNamespace(id=guild_id)))

    names = [item["name"] for item in economy_db.get_shop_items(guild_id)]
    assert name not in names


def test_readded_deleted_default_appears_via_additem_flow(tmp_path, monkeypatch):
    """Manually re-adding a deleted default (.additem flow) shows it in the shop and seeding does not duplicate it."""
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    guild_id = 333
    name = "🎆 Fireworks"

    economy_db.add_shop_item(guild_id, name=name, description="Reveal", price=100, is_default=True)
    assert economy_db.remove_shop_item_by_name(guild_id, name) is True
    assert economy_db.get_shop_items(guild_id) == []

    # Same as .additem: custom (non-default) insert of the same name.
    economy_db.add_shop_item(guild_id, name=name, description="", price=120, is_default=False)

    cog = economy_cog.Economy(bot=MagicMock())
    asyncio.run(cog._ensure_default_items(SimpleNamespace(id=guild_id)))
    asyncio.run(cog._ensure_default_items(SimpleNamespace(id=guild_id)))

    items = economy_db.get_shop_items(guild_id)
    matching = [it for it in items if it["name"] == name]
    assert len(matching) == 1
    assert matching[0]["price"] == 120
    assert matching[0]["is_default"] is False


# ------------------------------------------------------------------ #
# Behavioral tests for the ECO_SHOP_AUDIT fixes
# ------------------------------------------------------------------ #


class _Perms:
    def __init__(self, send=True, read=True, administrator=False):
        self.send_messages = send
        self.read_messages = read
        self.administrator = administrator


class _User:
    def __init__(self, uid, name, roles=None, guild_permissions=None, bot=False):
        self.id = uid
        self.display_name = name
        self.name = name
        self.mention = f"<@{uid}>"
        self.roles = roles or []
        self.guild_permissions = guild_permissions or _Perms()
        self.bot = bot

    def __eq__(self, other):
        if isinstance(other, _User):
            return self.id == other.id
        return NotImplemented


class _Role:
    def __init__(self, name):
        self.name = name
        self.mention = f"<@&role:{name}>"


_CATEGORY_IDS = iter(range(1, 10_000))


class _Channel:
    def __init__(self, cid, name, category=None, members=None):
        self.id = cid
        self.name = name
        self.category = category
        self.members = members or []
        self.mention = f"<#{cid}>"

    @property
    def category_id(self):
        return self.category.id if self.category else None

    def permissions_for(self, member):
        return _Perms(send=member in self.members, read=member in self.members)


class _Category:
    def __init__(self, name, channels=None):
        self.id = next(_CATEGORY_IDS)
        self.name = name
        self.text_channels = channels or []


class _Guild:
    def __init__(self, gid):
        self.id = gid
        self.categories = []
        self.channels = []
        self.roles = []
        self.members = []
        self.text_channels = []

    def cat(self, name):
        c = _Category(name)
        self.categories.append(c)
        return c

    def role(self, name):
        r = _Role(name)
        self.roles.append(r)
        return r

    def ch(self, cid, name, category=None, members=None):
        c = _Channel(cid, name, category=category, members=members)
        self.channels.append(c)
        if category is not None:
            category.text_channels.append(c)
        else:
            self.text_channels.append(c)
        return c

    def get_member(self, member_id):
        return next((m for m in self.members if m.id == member_id), None)

    def get_channel(self, cid):
        return next((c for c in self.channels if c.id == cid), None)


def _setup_guild_data(gid):
    save_guild_data(gid, {
        "rc_category_name": "ROLES",
        "alt_category_name": "ALT",
        "dead_rc_category_name": "DEAD",
        "houses_category_name": "HOUSES",
        "alive_role_name": "Alive",
        "sponsor_role_name": "Sponsor",
        "overseer_role_name": "Overseer",
        "whisper_logs_channel_name": "whisper-logs",
        "showwhispersender": False,
        "economy_collect_amount": 100,
        "peep_holes": {},
    })


def _make_ctx(guild, author, channel):
    ctx = SimpleNamespace()
    ctx.guild = guild
    ctx.author = author
    ctx.channel = channel
    ctx.bot = SimpleNamespace()
    ctx.sent = []
    ctx.embeds = []

    async def _send(content=None, embed=None, view=None, ephemeral=False):
        ctx.sent.append(content if content else (embed.title if embed else ""))
        if embed is not None:
            ctx.embeds.append(embed)
        return MagicMock()

    ctx.send = _send
    return ctx


def _make_interaction(guild, user, channel, client=None):
    i = SimpleNamespace()
    i.user = user
    i.guild = guild
    i.guild_id = guild.id
    i.channel = channel
    i.channel_id = channel.id
    i.client = client
    i.response = SimpleNamespace(sent=[], deferred=False)

    async def _send_message(content=None, embed=None, view=None, ephemeral=False):
        i.response.sent.append(content if content else (embed.title if embed else ""))
        return MagicMock()

    async def _defer(*args, **kwargs):
        i.response.deferred = True

    i.response.send_message = _send_message
    i.response.defer = _defer
    i.followup = SimpleNamespace(sent=[])

    async def _followup_send(content=None, embed=None, view=None, ephemeral=False):
        i.followup.sent.append(content if content else (embed.title if embed else ""))
        return MagicMock()

    i.followup.send = _followup_send
    i.original_response = AsyncMock(return_value=MagicMock(id=1))
    return i


# --- Fix 1: duplicate / empty-name add_shop_item --------------------------- #

def test_add_shop_item_duplicate_returns_existing_id(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    guild_id = 500
    first = economy_db.add_shop_item(guild_id, name="Fumo", description="", price=50, is_default=False)
    second = economy_db.add_shop_item(guild_id, name="Fumo", description="", price=99, is_default=False)
    assert first == second
    items = economy_db.get_shop_items(guild_id)
    assert len([it for it in items if it["name"] == "Fumo"]) == 1


def test_add_shop_item_empty_or_whitespace_name_returns_zero(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    guild_id = 501
    assert economy_db.add_shop_item(guild_id, name="", description="", price=50, is_default=False) == 0
    assert economy_db.add_shop_item(guild_id, name="   ", description="", price=50, is_default=False) == 0
    assert economy_db.get_shop_items(guild_id) == []


def test_additem_command_duplicate_does_not_add_second_row(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    guild_id = 502
    guild = _Guild(guild_id)
    me = _User(1, "Alice")
    ctx = _make_ctx(guild, me, guild.ch(1, "rc", category=guild.cat("ROLES")))
    cog = economy_cog.Economy(bot=MagicMock())
    asyncio.run(cog.additem.callback(cog, ctx, 50, name="Fumo"))
    asyncio.run(cog.additem.callback(cog, ctx, 99, name="Fumo"))
    items = economy_db.get_shop_items(guild_id)
    assert len([it for it in items if it["name"] == "Fumo"]) == 1
    assert items[0]["price"] == 50


def test_additem_command_rejects_whitespace_only_name(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    guild_id = 503
    guild = _Guild(guild_id)
    ctx = _make_ctx(guild, _User(1, "Alice"), guild.ch(1, "rc", category=guild.cat("ROLES")))
    cog = economy_cog.Economy(bot=MagicMock())
    asyncio.run(cog.additem.callback(cog, ctx, 50, name="   "))
    assert any("empty" in s for s in ctx.sent)
    assert economy_db.get_shop_items(guild_id) == []


# --- Fix 2: renaming a default item must not resurrect the original --------- #

def test_rename_default_item_does_not_resurrect_original(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    guild_id = 504
    economy_db.add_shop_item(guild_id, name="🎆 Fireworks", description="Reveal", price=100, is_default=True)
    assert economy_db.update_shop_item_by_name(guild_id, "🎆 Fireworks", name="💥 Booms") is True
    names = [it["name"] for it in economy_db.get_shop_items(guild_id)]
    assert names == ["💥 Booms"]

    cog = economy_cog.Economy(bot=MagicMock())
    asyncio.run(cog._ensure_default_items(SimpleNamespace(id=guild_id)))
    names = [it["name"] for it in economy_db.get_shop_items(guild_id)]
    assert "🎆 Fireworks" not in names
    assert "💥 Booms" in names


def test_rename_default_item_stays_renamed_across_restart(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    guild_id = 505
    economy_db.add_shop_item(guild_id, name="👟 Shoes", description="", price=250, is_default=True)
    assert economy_db.update_shop_item_by_name(guild_id, "👟 Shoes", name="👟 Sneakers") is True

    monkeypatch.setattr(economy_db, "_DB_READY", False)
    monkeypatch.setattr(economy_db, "_BOT_DB_MIGRATED", False)

    cog = economy_cog.Economy(bot=MagicMock())
    asyncio.run(cog._ensure_default_items(SimpleNamespace(id=guild_id)))

    names = [it["name"] for it in economy_db.get_shop_items(guild_id)]
    assert "👟 Shoes" not in names
    assert "👟 Sneakers" in names


def test_rename_default_item_then_rename_back_stays_single(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    guild_id = 506
    economy_db.add_shop_item(guild_id, name="🎆 Fireworks", description="Reveal", price=100, is_default=True)
    assert economy_db.update_shop_item_by_name(guild_id, "🎆 Fireworks", name="💥 Booms") is True
    assert economy_db.update_shop_item_by_name(guild_id, "💥 Booms", name="🎆 Fireworks") is True
    names = [it["name"] for it in economy_db.get_shop_items(guild_id)]
    assert names == ["🎆 Fireworks"]

    cog = economy_cog.Economy(bot=MagicMock())
    asyncio.run(cog._ensure_default_items(SimpleNamespace(id=guild_id)))
    names = [it["name"] for it in economy_db.get_shop_items(guild_id)]
    assert names.count("🎆 Fireworks") == 1


# --- Fix 3: atomic buy_shop_item -------------------------------------------- #

def test_buy_shop_item_atomic_success(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    guild_id, channel_id = 507, 1
    item_id = economy_db.add_shop_item(guild_id, name="Fumo", description="", price=50, is_default=False)
    economy_db.set_economy_channel_balance(guild_id, channel_id, 200)
    ok, qty = economy_db.buy_shop_item(guild_id, channel_id, item_id, 50, 3)
    assert ok is True and qty == 3
    assert economy_db.get_economy_channel_balance(guild_id, channel_id) == 50
    assert economy_db.add_inventory_item_channel(guild_id, channel_id, item_id, 0) == 3


def test_buy_shop_item_insufficient_balance_no_changes(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    guild_id, channel_id = 508, 1
    item_id = economy_db.add_shop_item(guild_id, name="Fumo", description="", price=50, is_default=False)
    economy_db.set_economy_channel_balance(guild_id, channel_id, 10)
    ok, qty = economy_db.buy_shop_item(guild_id, channel_id, item_id, 50, 1)
    assert ok is False and qty == 0
    assert economy_db.get_economy_channel_balance(guild_id, channel_id) == 10
    assert economy_db.add_inventory_item_channel(guild_id, channel_id, item_id, 0) == 0


def test_buy_shop_item_stale_item_does_not_deduct(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    guild_id, channel_id = 509, 1
    item_id = economy_db.add_shop_item(guild_id, name="Fumo", description="", price=50, is_default=False)
    economy_db.remove_shop_item(guild_id, item_id)
    economy_db.set_economy_channel_balance(guild_id, channel_id, 100)
    ok, qty = economy_db.buy_shop_item(guild_id, channel_id, item_id, 50, 1)
    assert ok is False and qty == 0
    assert economy_db.get_economy_channel_balance(guild_id, channel_id) == 100


def test_buy_command_success_uses_atomic_purchase(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    guild_id = 510
    guild = _Guild(guild_id)
    rc = guild.cat("ROLES")
    me = _User(1, "Alice")
    rc_ch = guild.ch(1, "rc", category=rc, members=[me])
    _setup_guild_data(guild_id)
    item_id = economy_db.add_shop_item(guild_id, name="Fumo", description="", price=50, is_default=False)
    economy_db.set_economy_channel_balance(guild_id, rc_ch.id, 200)
    cog = economy_cog.Economy(bot=MagicMock())
    ctx = _make_ctx(guild, me, rc_ch)
    asyncio.run(cog.buy.callback(cog, ctx, "Fumo", 3))
    assert economy_db.get_economy_channel_balance(guild_id, rc_ch.id) == 50
    assert economy_db.add_inventory_item_channel(guild_id, rc_ch.id, item_id, 0) == 3
    assert any("Purchase successful" in s for s in ctx.sent)


def test_buy_command_insufficient_balance_no_changes(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    guild_id = 511
    guild = _Guild(guild_id)
    rc = guild.cat("ROLES")
    me = _User(1, "Alice")
    rc_ch = guild.ch(1, "rc", category=rc, members=[me])
    _setup_guild_data(guild_id)
    item_id = economy_db.add_shop_item(guild_id, name="Fumo", description="", price=50, is_default=False)
    economy_db.set_economy_channel_balance(guild_id, rc_ch.id, 10)
    cog = economy_cog.Economy(bot=MagicMock())
    ctx = _make_ctx(guild, me, rc_ch)
    asyncio.run(cog.buy.callback(cog, ctx, "Fumo", 3))
    assert economy_db.get_economy_channel_balance(guild_id, rc_ch.id) == 10
    assert economy_db.add_inventory_item_channel(guild_id, rc_ch.id, item_id, 0) == 0
    assert any("don't have enough" in s for s in ctx.sent)


def test_buy_command_stale_item_no_deduct(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    guild_id = 512
    guild = _Guild(guild_id)
    rc = guild.cat("ROLES")
    me = _User(1, "Alice")
    rc_ch = guild.ch(1, "rc", category=rc, members=[me])
    _setup_guild_data(guild_id)
    other_id = economy_db.add_shop_item(guild_id, name="Fumo", description="", price=50, is_default=False)
    economy_db.set_economy_channel_balance(guild_id, rc_ch.id, 100)
    cog = economy_cog.Economy(bot=MagicMock())
    ctx = _make_ctx(guild, me, rc_ch)
    with patch.object(economy_cog, "get_shop_item_by_name",
                      return_value={"id": 9999, "name": "Fumo", "price": 50}):
        asyncio.run(cog.buy.callback(cog, ctx, "Fumo", 1))
    assert economy_db.get_economy_channel_balance(guild_id, rc_ch.id) == 100
    assert economy_db.add_inventory_item_channel(guild_id, rc_ch.id, other_id, 0) == 0
    assert any("Item not found" in s for s in ctx.sent)


def test_shopview_buy_atomic_success(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    guild_id = 513
    guild = _Guild(guild_id)
    rc = guild.cat("ROLES")
    ch = guild.ch(1, "rc", category=rc)
    item_id = economy_db.add_shop_item(guild_id, name="Fumo", description="", price=50, is_default=False)
    items = economy_db.get_shop_items(guild_id)
    economy_db.set_economy_channel_balance(guild_id, ch.id, 100)

    async def run():
        invoker = SimpleNamespace(id=5, guild_permissions=_Perms(administrator=True))
        view = economy_cog.ShopView(["page"], [items], invoker, guild_id, ch.id)
        view.selected_item_id = item_id
        i = _make_interaction(guild, invoker, ch)
        await view.btn_buy.callback.callback(view, i, None)
        return i

    i = asyncio.run(run())
    assert economy_db.get_economy_channel_balance(guild_id, ch.id) == 50
    assert economy_db.add_inventory_item_channel(guild_id, ch.id, item_id, 0) == 1
    assert any("Bought" in s for s in i.response.sent)


def test_shopview_buy_insufficient_balance_no_changes(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    guild_id = 514
    guild = _Guild(guild_id)
    rc = guild.cat("ROLES")
    ch = guild.ch(1, "rc", category=rc)
    item_id = economy_db.add_shop_item(guild_id, name="Fumo", description="", price=50, is_default=False)
    items = economy_db.get_shop_items(guild_id)
    economy_db.set_economy_channel_balance(guild_id, ch.id, 10)

    async def run():
        invoker = SimpleNamespace(id=5, guild_permissions=_Perms(administrator=True))
        view = economy_cog.ShopView(["page"], [items], invoker, guild_id, ch.id)
        view.selected_item_id = item_id
        i = _make_interaction(guild, invoker, ch)
        await view.btn_buy.callback.callback(view, i, None)
        return i

    i = asyncio.run(run())
    assert economy_db.get_economy_channel_balance(guild_id, ch.id) == 10
    assert economy_db.add_inventory_item_channel(guild_id, ch.id, item_id, 0) == 0
    assert any("Need" in s for s in i.response.sent)


# --- Fix 5: UI Whisper timeout ---------------------------------------------- #

def test_ui_whisper_has_bounded_timeout():
    src = inspect.getsource(economy_cog.InventoryView._do_whisper)
    assert "asyncio.wait_for(done.wait()" in src
    assert "View(timeout=300)" in src


def test_ui_whisper_times_out_gracefully(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    guild_id = 515
    guild = _Guild(guild_id)
    alive = guild.role("Alive")
    me = _User(1, "Alice", roles=[alive])
    guild.members = [me]
    _setup_guild_data(guild_id)
    i = _make_interaction(guild, me, guild.ch(1, "house-1"))
    with patch("cogs.economy_cog.asyncio.wait_for", new=AsyncMock(side_effect=asyncio.TimeoutError())):
        ok = asyncio.run(economy_cog.InventoryView._do_whisper(None, i))
    assert ok is False


# --- Fix 6: UI Broom house-only rule ---------------------------------------- #

def test_ui_broom_blocked_outside_house(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    guild_id = 516
    guild = _Guild(guild_id)
    rc = guild.cat("ROLES")
    me = _User(1, "Alice")
    rc_ch = guild.ch(1, "rc", category=rc, members=[me])
    _setup_guild_data(guild_id)
    i = _make_interaction(guild, me, rc_ch)
    ok = asyncio.run(economy_cog.InventoryView._do_broom(None, i))
    assert ok is False
    assert i.response.sent and "House channel" in i.response.sent[-1]
    assert i.response.deferred is False


def test_ui_broom_allowed_in_house_then_times_out(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    guild_id = 517
    guild = _Guild(guild_id)
    houses = guild.cat("HOUSES")
    me = _User(1, "Alice")
    house_ch = guild.ch(1, "house-1", category=houses, members=[me])
    _setup_guild_data(guild_id)
    i = _make_interaction(guild, me, house_ch)
    i.client = SimpleNamespace(wait_for=AsyncMock(side_effect=asyncio.TimeoutError()))

    async def ch_send(content=None, embed=None, file=None, delete_after=None):
        return SimpleNamespace(id=1)

    i.channel.send = ch_send
    ok = asyncio.run(economy_cog.InventoryView._do_broom(None, i))
    assert ok is False
    assert i.response.deferred is True


def test_use_broom_command_blocked_outside_house(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    guild_id = 518
    guild = _Guild(guild_id)
    rc = guild.cat("ROLES")
    me = _User(1, "Alice", roles=[guild.role("Alive")])
    rc_ch = guild.ch(1, "rc", category=rc, members=[me])
    guild.members.append(me)
    _setup_guild_data(guild_id)
    economy_db.add_shop_item(guild_id, name="🧹 Broom", description="", price=50, is_default=False)
    cog = economy_cog.Economy(bot=MagicMock())
    ctx = _make_ctx(guild, me, rc_ch)
    asyncio.run(cog.use_item.callback(cog, ctx, item_name="🧹 Broom"))
    assert any("House channel" in s for s in ctx.sent)


def test_use_broom_command_checks_inventory_in_rolechat(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    guild_id = 519
    guild = _Guild(guild_id)
    houses = guild.cat("HOUSES")
    rc = guild.cat("ROLES")
    alive = guild.role("Alive")
    me = _User(1, "Alice", roles=[alive])
    rc_ch = guild.ch(1, "rc", category=rc, members=[me])
    house_ch = guild.ch(2, "house-1", category=houses, members=[me])
    guild.members.append(me)
    _setup_guild_data(guild_id)
    economy_db.add_shop_item(guild_id, name="🧹 Broom", description="", price=50, is_default=False)
    cog = economy_cog.Economy(bot=MagicMock())
    ctx = _make_ctx(guild, me, house_ch)
    asyncio.run(cog.use_item.callback(cog, ctx, item_name="🧹 Broom"))
    assert any("don't have that item" in s for s in ctx.sent)


# --- Fix 7: Peep Hole UI follows the command path ---------------------------- #

def test_ui_peephole_activates_in_house(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    guild_id = 520
    guild = _Guild(guild_id)
    houses = guild.cat("HOUSES")
    alive = guild.role("Alive")
    me = _User(1, "Alice", roles=[alive])
    house_ch = guild.ch(1, "house-1", category=houses, members=[me])
    _setup_guild_data(guild_id)
    i = _make_interaction(guild, me, house_ch)
    ok = asyncio.run(economy_cog.InventoryView._do_peephole(None, i))
    assert ok is True
    assert load_guild_data(guild_id)["peep_holes"].get(str(house_ch.id)) is not None


def test_ui_peephole_blocked_outside_house(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    guild_id = 521
    guild = _Guild(guild_id)
    rc = guild.cat("ROLES")
    me = _User(1, "Alice", roles=[guild.role("Alive")])
    rc_ch = guild.ch(1, "rc", category=rc, members=[me])
    _setup_guild_data(guild_id)
    i = _make_interaction(guild, me, rc_ch)
    ok = asyncio.run(economy_cog.InventoryView._do_peephole(None, i))
    assert ok is False
    assert i.response.sent and "House channel" in i.response.sent[-1]


def test_use_peephole_command_activates_in_house(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    guild_id = 522
    guild = _Guild(guild_id)
    houses = guild.cat("HOUSES")
    rc = guild.cat("ROLES")
    alive = guild.role("Alive")
    me = _User(1, "Alice", roles=[alive])
    rc_ch = guild.ch(1, "rc", category=rc, members=[me])
    house_ch = guild.ch(2, "house-1", category=houses, members=[me])
    guild.members.append(me)
    _setup_guild_data(guild_id)
    item_id = economy_db.add_shop_item(guild_id, name="🔭 Peep Hole", description="", price=100, is_default=False)
    economy_db.add_inventory_item_channel(guild_id, rc_ch.id, item_id, 1)
    cog = economy_cog.Economy(bot=MagicMock())
    ctx = _make_ctx(guild, me, house_ch)
    asyncio.run(cog.use_item.callback(cog, ctx, item_name="🔭 Peep Hole"))
    assert load_guild_data(guild_id)["peep_holes"].get(str(house_ch.id)) is not None
    assert economy_db.add_inventory_item_channel(guild_id, rc_ch.id, item_id, 0) == 0


def test_use_peephole_command_blocked_outside_house(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    guild_id = 523
    guild = _Guild(guild_id)
    rc = guild.cat("ROLES")
    me = _User(1, "Alice", roles=[guild.role("Alive")])
    rc_ch = guild.ch(1, "rc", category=rc, members=[me])
    guild.members.append(me)
    _setup_guild_data(guild_id)
    economy_db.add_shop_item(guild_id, name="🔭 Peep Hole", description="", price=100, is_default=False)
    cog = economy_cog.Economy(bot=MagicMock())
    ctx = _make_ctx(guild, me, rc_ch)
    asyncio.run(cog.use_item.callback(cog, ctx, item_name="🔭 Peep Hole"))
    assert any("House channel" in s for s in ctx.sent)


# --- Fix 8: empty/whitespace names rejected at command level ----------------- #

def test_edititem_rejects_empty_new_name(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    guild_id = 524
    economy_db.add_shop_item(guild_id, name="Fumo", description="", price=50, is_default=False)
    guild = _Guild(guild_id)
    me = _User(1, "Alice")
    ctx = _make_ctx(guild, me, guild.ch(1, "rc", category=guild.cat("ROLES")))
    cog = economy_cog.Economy(bot=MagicMock())
    asyncio.run(cog.edititem.callback(cog, ctx, "name", "Fumo", new_value="   "))
    assert any("empty" in s for s in ctx.sent)
    items = economy_db.get_shop_items(guild_id)
    assert [it["name"] for it in items] == ["Fumo"]


def test_edititem_rename_to_duplicate_reports_cleanly(tmp_path, monkeypatch):
    """Renaming an item to a name that already exists must not crash and must
    tell the admin why the rename was rejected."""
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    guild_id = 525
    economy_db.add_shop_item(guild_id, name="Fumo", description="", price=50, is_default=False)
    economy_db.add_shop_item(guild_id, name="Sword", description="", price=60, is_default=False)
    guild = _Guild(guild_id)
    me = _User(1, "Alice")
    ctx = _make_ctx(guild, me, guild.ch(1, "rc", category=guild.cat("ROLES")))
    cog = economy_cog.Economy(bot=MagicMock())
    asyncio.run(cog.edititem.callback(cog, ctx, "name", "Fumo", new_value="Sword"))
    assert any("already exists" in s for s in ctx.sent)
    assert sorted(i["name"] for i in economy_db.get_shop_items(guild_id)) == ["Fumo", "Sword"]


# ------------------------------------------------------------------ #
# Database separation: bot.db -> economy.db migration tests
# ------------------------------------------------------------------ #


def _make_source_bot_db(tmp_path):
    """Create a temp bot.db with economy tables + data plus one non-economy table."""
    import sqlite3
    src_path = tmp_path / "bot.db"
    conn = sqlite3.connect(str(src_path))
    conn.executescript(
        """
        CREATE TABLE economy_shop_items (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            guild_id INTEGER NOT NULL,
            name TEXT NOT NULL,
            description TEXT,
            price INTEGER NOT NULL,
            is_default INTEGER NOT NULL DEFAULT 0
        );
        CREATE TABLE economy_removed_default_items (
            guild_id INTEGER NOT NULL,
            name TEXT NOT NULL,
            PRIMARY KEY (guild_id, name)
        );
        CREATE TABLE economy_accounts (
            guild_id INTEGER NOT NULL,
            user_id INTEGER NOT NULL,
            wallet INTEGER NOT NULL DEFAULT 0,
            bank INTEGER NOT NULL DEFAULT 0,
            last_collect_at TEXT,
            PRIMARY KEY (guild_id, user_id)
        );
        CREATE TABLE economy_inventory (
            guild_id INTEGER NOT NULL,
            user_id INTEGER NOT NULL,
            item_id INTEGER NOT NULL,
            quantity INTEGER NOT NULL DEFAULT 0,
            PRIMARY KEY (guild_id, user_id, item_id),
            FOREIGN KEY (item_id) REFERENCES economy_shop_items(id) ON DELETE CASCADE
        );
        CREATE TABLE economy_channel_balance (
            guild_id INTEGER NOT NULL,
            channel_id INTEGER NOT NULL,
            balance INTEGER NOT NULL DEFAULT 0,
            PRIMARY KEY (guild_id, channel_id)
        );
        CREATE TABLE economy_channel_inventory (
            guild_id INTEGER NOT NULL,
            channel_id INTEGER NOT NULL,
            item_id INTEGER NOT NULL,
            quantity INTEGER NOT NULL DEFAULT 0,
            PRIMARY KEY (guild_id, channel_id, item_id),
            FOREIGN KEY (item_id) REFERENCES economy_shop_items(id) ON DELETE CASCADE
        );
        CREATE TABLE non_economy_table (
            id INTEGER PRIMARY KEY,
            note TEXT
        );
        INSERT INTO economy_shop_items (id, guild_id, name, description, price, is_default) VALUES
            (101, 1, 'Fumo', 'c', 50, 0),
            (102, 1, 'Bomb', 'b', 500, 1);
        INSERT INTO economy_removed_default_items (guild_id, name) VALUES (1, 'Old Boom');
        INSERT INTO economy_accounts (guild_id, user_id, wallet, bank, last_collect_at) VALUES
            (1, 10, 5, 6, '2024-01-01T00:00:00'),
            (1, 11, 7, 8, NULL);
        INSERT INTO economy_inventory (guild_id, user_id, item_id, quantity) VALUES
            (1, 10, 101, 3),
            (1, 10, 999, 9);
        INSERT INTO economy_channel_balance (guild_id, channel_id, balance) VALUES (1, 20, 42);
        INSERT INTO economy_channel_inventory (guild_id, channel_id, item_id, quantity) VALUES
            (1, 20, 102, 4),
            (1, 20, 999, 7);
        INSERT INTO non_economy_table (id, note) VALUES (1, 'keep me');
        """
    )
    conn.commit()
    conn.close()
    return src_path


def _point_at_source_bot_db(tmp_path, monkeypatch):
    """Patch bot_db (migration source) and economy_db (destination) to temp files."""
    import utils.bot_db as bot_db
    import utils.economy_db as economy_db
    src = _make_source_bot_db(tmp_path)
    monkeypatch.setattr(bot_db, "DB_DIR", str(tmp_path))
    monkeypatch.setattr(bot_db, "DB_PATH", str(src))
    monkeypatch.setattr(economy_db, "DB_DIR", str(tmp_path))
    monkeypatch.setattr(economy_db, "DB_PATH", str(tmp_path / "economy.db"))
    monkeypatch.setattr(economy_db, "_DB_READY", False)
    monkeypatch.setattr(economy_db, "_BOT_DB_MIGRATED", False)
    return src


def test_migration_copies_economy_tables_with_ids(tmp_path, monkeypatch):
    import sqlite3
    import utils.economy_db as economy_db
    src = _point_at_source_bot_db(tmp_path, monkeypatch)

    assert [it["id"] for it in economy_db.get_shop_items(1)] == [101, 102]
    assert economy_db.get_removed_default_items(1) == {"Old Boom"}
    assert economy_db.get_economy_account(1, 10) == (5, 6)
    assert economy_db.get_economy_account(1, 11) == (7, 8)
    assert [(i["item_id"], i["quantity"]) for i in economy_db.get_inventory(1, 10)] == [(101, 3)]
    assert economy_db.get_economy_channel_balance(1, 20) == 42
    assert [(i["item_id"], i["quantity"]) for i in economy_db.get_inventory_channel(1, 20)] == [(102, 4)]

    # Orphaned inventory rows (item_id 999 not in shop_items) are skipped.
    assert all(i["item_id"] != 999 for i in economy_db.get_inventory(1, 10))
    assert all(i["item_id"] != 999 for i in economy_db.get_inventory_channel(1, 20))

    conn = sqlite3.connect(str(src))
    conn.row_factory = sqlite3.Row
    assert conn.execute("SELECT COUNT(*) c FROM economy_shop_items").fetchone()["c"] == 2
    assert conn.execute("SELECT COUNT(*) c FROM non_economy_table").fetchone()["c"] == 1
    assert conn.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='economy_accounts'").fetchone() is not None
    conn.close()

    assert economy_db._get_migration_marker() == "1"


def test_migration_is_idempotent(tmp_path, monkeypatch):
    import utils.economy_db as economy_db
    src = _point_at_source_bot_db(tmp_path, monkeypatch)

    economy_db.get_shop_items(1)
    # Simulate restart: clear in-memory flags, then run the migration again.
    monkeypatch.setattr(economy_db, "_DB_READY", False)
    monkeypatch.setattr(economy_db, "_BOT_DB_MIGRATED", False)
    economy_db.get_shop_items(1)
    # Force a direct re-run even with the marker present; nothing duplicates.
    economy_db._migrate_from_bot_db()
    assert len(economy_db.get_shop_items(1)) == 2
    assert economy_db.get_economy_account(1, 10) == (5, 6)
    assert economy_db.get_economy_channel_balance(1, 20) == 42
    assert economy_db._get_migration_marker() == "1"


def test_post_migration_writes_go_to_economy_db(tmp_path, monkeypatch):
    import sqlite3
    import utils.economy_db as economy_db
    src = _point_at_source_bot_db(tmp_path, monkeypatch)

    economy_db.get_shop_items(1)
    economy_db.add_shop_item(1, "New Item", "", 100, is_default=False)
    economy_db.set_economy_channel_balance(1, 30, 77)

    assert "New Item" in [it["name"] for it in economy_db.get_shop_items(1)]
    assert economy_db.get_economy_channel_balance(1, 30) == 77

    conn = sqlite3.connect(str(src))
    conn.row_factory = sqlite3.Row
    names = [r["name"] for r in conn.execute("SELECT name FROM economy_shop_items").fetchall()]
    balances = [r["balance"] for r in conn.execute("SELECT balance FROM economy_channel_balance").fetchall()]
    conn.close()
    assert "New Item" not in names
    assert 77 not in balances


def test_migration_preserves_autoincrement_sequence(tmp_path, monkeypatch):
    """After copying explicit ids (101, 102), the next insert must not collide."""
    import utils.economy_db as economy_db
    _point_at_source_bot_db(tmp_path, monkeypatch)
    economy_db.get_shop_items(1)
    new_id = economy_db.add_shop_item(1, "Third", "", 99, is_default=False)
    assert new_id == 103


# ------------------------------------------------------------------ #
# Comprehensive DB-layer tests (coverage ported from the audit harness)
# ------------------------------------------------------------------ #

def test_shop_items_ordered_by_price_then_name(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 700
    economy_db.add_shop_item(gid, "Sword", "", 500, is_default=False)
    economy_db.add_shop_item(gid, "Axe", "", 300, is_default=False)
    economy_db.add_shop_item(gid, "Bow", "", 300, is_default=False)
    assert [i["name"] for i in economy_db.get_shop_items(gid)] == ["Axe", "Bow", "Sword"]


def test_duplicate_add_keeps_original_price(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 701
    economy_db.add_shop_item(gid, "Fumo", "", 50, is_default=False)
    economy_db.add_shop_item(gid, "Fumo", "", 99, is_default=False)
    items = economy_db.get_shop_items(gid)
    assert len(items) == 1 and items[0]["price"] == 50


def test_same_name_different_guilds_isolated(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    economy_db.add_shop_item(702, "Sword", "", 10, is_default=False)
    economy_db.add_shop_item(703, "Sword", "", 20, is_default=False)
    assert len(economy_db.get_shop_items(702)) == 1
    assert len(economy_db.get_shop_items(703)) == 1
    assert economy_db.get_shop_items(702)[0]["price"] == 10
    assert economy_db.get_shop_items(703)[0]["price"] == 20


def test_negative_price_clamped_to_zero(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 704
    economy_db.add_shop_item(gid, "Neg", "", -50, is_default=False)
    assert economy_db.get_shop_items(gid)[0]["price"] == 0
    economy_db.update_shop_item_by_name(gid, "neg", price=-999)
    assert economy_db.get_shop_items(gid)[0]["price"] == 0


def test_normalized_partial_match(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 705
    economy_db.add_shop_item(gid, "🎆 Fire works", "", 5, is_default=False)
    assert economy_db.get_shop_item_by_name(gid, "FIREWORK") is not None
    assert economy_db.get_shop_item_by_name(gid, "ork")["name"] == "🎆 Fire works"
    assert economy_db.get_shop_item_by_name(gid, "🎆") is None
    assert economy_db.get_shop_item_by_name(gid, "") is None
    assert economy_db.get_shop_item_by_name(gid, "nope") is None


def test_add_inventory_channel_clamps_and_hides_zero(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid, ch = 706, 1
    iid = economy_db.add_shop_item(gid, "Coin", "", 1, is_default=False)
    assert economy_db.add_inventory_item_channel(gid, ch, iid, 3) == 3
    assert economy_db.add_inventory_item_channel(gid, ch, iid, -5) == 0
    assert economy_db.get_inventory_channel(gid, ch) == []


def test_update_channel_balance_clamps_to_zero(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid, ch = 707, 1
    economy_db.set_economy_channel_balance(gid, ch, 50)
    assert economy_db.update_economy_channel_balance(gid, ch, -500) == 0


def test_fk_cascade_removes_inventory_on_shop_delete(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid, ch = 708, 1
    iid = economy_db.add_shop_item(gid, "Disposable", "", 10, is_default=False)
    economy_db.add_inventory_item_channel(gid, ch, iid, 5)
    economy_db.remove_shop_item(gid, iid)
    assert economy_db.get_inventory_channel(gid, ch) == []


def test_add_inventory_for_deleted_item_returns_zero(tmp_path, monkeypatch):
    """add_inventory_item_channel tolerates an item deleted mid-request."""
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid, ch = 709, 1
    iid = economy_db.add_shop_item(gid, "Perish", "", 10, is_default=False)
    economy_db.remove_shop_item(gid, iid)
    assert economy_db.add_inventory_item_channel(gid, ch, iid, 1) == 0


def test_add_inventory_user_for_deleted_item_returns_zero(tmp_path, monkeypatch):
    """User-based add_inventory_item tolerates an item deleted mid-request."""
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid, uid = 709, 1
    iid = economy_db.add_shop_item(gid, "Perish", "", 10, is_default=False)
    economy_db.remove_shop_item(gid, iid)
    assert economy_db.add_inventory_item(gid, uid, iid, 1) == 0


def test_rename_to_existing_name_returns_false(tmp_path, monkeypatch):
    """Renaming to a name that already exists fails cleanly (no crash) and
    leaves both items intact."""
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 710
    economy_db.add_shop_item(gid, "Fumo", "", 50, is_default=False)
    economy_db.add_shop_item(gid, "Sword", "", 60, is_default=False)
    assert economy_db.update_shop_item_by_name(gid, "fumo", name="Sword") is False
    assert sorted(i["name"] for i in economy_db.get_shop_items(gid)) == ["Fumo", "Sword"]


def test_buy_shop_item_rejects_non_positive_quantity(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid, ch = 711, 1
    iid = economy_db.add_shop_item(gid, "Fumo", "", 100, is_default=False)
    economy_db.set_economy_channel_balance(gid, ch, 1000)
    ok, qty = economy_db.buy_shop_item(gid, ch, iid, 100, -1)
    assert ok is False
    assert qty == 0
    assert economy_db.get_economy_channel_balance(gid, ch) == 1000


def test_transfer_channel_balance_rejects_negative_amount(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 712
    economy_db.set_economy_channel_balance(gid, 1, 100)
    economy_db.set_economy_channel_balance(gid, 2, 0)
    assert economy_db.transfer_channel_balance(gid, 1, 2, -50) is False
    assert economy_db.get_economy_channel_balance(gid, 1) == 100
    assert economy_db.get_economy_channel_balance(gid, 2) == 0


def test_transfer_economy_balance_rejects_negative_amount(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 713
    economy_db.set_economy_account(gid, 1, 100, 0)
    economy_db.set_economy_account(gid, 2, 0, 0)
    assert economy_db.transfer_economy_balance(gid, 1, 2, -50) is False
    assert economy_db.get_economy_account(gid, 1) == (100, 0)
    assert economy_db.get_economy_account(gid, 2) == (0, 0)


def test_transfer_channel_balance_atomic_success_and_fail(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 714
    economy_db.set_economy_channel_balance(gid, 1, 100)
    economy_db.set_economy_channel_balance(gid, 2, 0)
    assert economy_db.transfer_channel_balance(gid, 1, 2, 500) is False
    assert economy_db.get_economy_channel_balance(gid, 1) == 100
    assert economy_db.get_economy_channel_balance(gid, 2) == 0
    assert economy_db.transfer_channel_balance(gid, 1, 2, 100) is True
    assert economy_db.get_economy_channel_balance(gid, 1) == 0
    assert economy_db.get_economy_channel_balance(gid, 2) == 100


def test_transfer_economy_balance_atomic_success_and_fail(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 715
    economy_db.set_economy_account(gid, 1, 100, 0)
    economy_db.set_economy_account(gid, 2, 0, 0)
    assert economy_db.transfer_economy_balance(gid, 1, 2, 500) is False
    assert economy_db.get_economy_account(gid, 1) == (100, 0)
    assert economy_db.transfer_economy_balance(gid, 1, 2, 40) is True
    assert economy_db.get_economy_account(gid, 1) == (60, 0)
    assert economy_db.get_economy_account(gid, 2) == (40, 0)


def test_sell_refund_exact_half_price_floor(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid, ch = 716, 1
    iid = economy_db.add_shop_item(gid, "Fumo", "", 51, is_default=False)
    economy_db.add_inventory_item_channel(gid, ch, iid, 1)
    before = economy_db.get_economy_channel_balance(gid, ch)
    economy_db.add_inventory_item_channel(gid, ch, iid, -1)
    economy_db.update_economy_channel_balance(gid, ch, 51 // 2)
    assert economy_db.get_economy_channel_balance(gid, ch) == before + 25
    assert economy_db.get_inventory_channel(gid, ch) == []


def test_zero_price_buy_succeeds(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid, ch = 717, 1
    iid = economy_db.add_shop_item(gid, "Freebie", "", 0, is_default=False)
    ok, qty = economy_db.buy_shop_item(gid, ch, iid, 0, 1)
    assert ok is True and qty == 1
    assert economy_db.get_economy_channel_balance(gid, ch) == 0


def test_top_economy_channels_sorted_desc(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 718
    economy_db.set_economy_channel_balance(gid, 1, 50)
    economy_db.set_economy_channel_balance(gid, 2, 300)
    economy_db.set_economy_channel_balance(gid, 3, 0)
    top = economy_db.get_top_economy_channels(gid, 10)
    assert [e["channel_id"] for e in top] == [2, 1]
    assert [e["balance"] for e in top] == [300, 50]


def test_get_top_economy_users_sorted_desc(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 719
    economy_db.set_economy_account(gid, 1, 50, 0)
    economy_db.set_economy_account(gid, 2, 0, 300)
    economy_db.set_economy_account(gid, 3, 10, 10)
    top = economy_db.get_top_economy_users(gid, 10)
    assert [e["user_id"] for e in top] == [2, 1, 3]
    assert top[0]["total"] == 300


def test_seed_default_items_idempotent(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 720
    cog = economy_cog.Economy(bot=MagicMock())
    asyncio.run(cog._ensure_default_items(SimpleNamespace(id=gid)))
    asyncio.run(cog._ensure_default_items(SimpleNamespace(id=gid)))
    items = economy_db.get_shop_items(gid)
    assert len(items) == 6
    assert all(i["is_default"] for i in items)


def test_normalized_name_collision_allows_separate_custom_row(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 721
    cog = economy_cog.Economy(bot=MagicMock())
    asyncio.run(cog._ensure_default_items(SimpleNamespace(id=gid)))
    economy_db.add_shop_item(gid, "🎆 Fire works", "", 999, is_default=False)
    asyncio.run(cog._ensure_default_items(SimpleNamespace(id=gid)))
    names = [i["name"] for i in economy_db.get_shop_items(gid)]
    assert names.count("🎆 Fireworks") == 1
    assert names.count("🎆 Fire works") == 1
    assert economy_db.get_shop_item_by_name(gid, "firework") is not None


def test_shop_empty_after_all_defaults_removed(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 722
    cog = economy_cog.Economy(bot=MagicMock())
    asyncio.run(cog._ensure_default_items(SimpleNamespace(id=gid)))
    for item in economy_db.get_shop_items(gid):
        economy_db.remove_shop_item_by_name(gid, item["name"])
    guild = _Guild(gid)
    ctx = _make_ctx(guild, _User(1, "Alice"), guild.ch(1, "rc", category=guild.cat("ROLES")))
    asyncio.run(cog.shop.callback(cog, ctx))
    assert any("shop is empty" in s.lower() for s in ctx.sent)


# ------------------------------------------------------------------ #
# Comprehensive command-level behavioral tests
# ------------------------------------------------------------------ #

def _build_world(gid):
    """Rolechat economy world: categories, roles, members, guild data, cog."""
    guild = _Guild(gid)
    rc = guild.cat("ROLES")
    alt = guild.cat("ALT")
    dead = guild.cat("DEAD")
    houses = guild.cat("HOUSES")
    alive = guild.role("Alive")
    sponsor = guild.role("Sponsor")
    overseer = guild.role("Overseer")
    me = _User(1, "Alice", roles=[alive])
    bob = _User(2, "Bob", roles=[alive])
    rc_alice = guild.ch(101, "alice-rc", category=rc, members=[me])
    rc_bob = guild.ch(102, "bob-rc", category=rc, members=[bob])
    house1 = guild.ch(201, "house-1", category=houses, members=[me, bob])
    guild.members = [me, bob]
    alive.members = [me, bob]
    _setup_guild_data(gid)
    cog = economy_cog.Economy(bot=SimpleNamespace())
    return guild, rc, houses, alive, me, bob, rc_alice, rc_bob, house1, cog


def test_buy_rejects_non_positive_quantity(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 723
    guild, rc, houses, alive, me, bob, rc_alice, rc_bob, house1, cog = _build_world(gid)
    asyncio.run(cog._ensure_default_items(guild))
    ctx = _make_ctx(guild, me, rc_alice)
    asyncio.run(cog.buy.callback(cog, ctx, "firework", 0))
    assert any("Quantity must be at least 1" in s for s in ctx.sent)
    ctx2 = _make_ctx(guild, me, rc_alice)
    asyncio.run(cog.buy.callback(cog, ctx2, "firework", -3))
    assert any("Quantity must be at least 1" in s for s in ctx2.sent)


def test_buy_happy_path_deducts_and_adds(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 724
    guild, rc, houses, alive, me, bob, rc_alice, rc_bob, house1, cog = _build_world(gid)
    asyncio.run(cog._ensure_default_items(guild))
    fw = economy_db.get_shop_item_by_name(gid, "firework")
    economy_db.set_economy_channel_balance(gid, rc_alice.id, 500)
    ctx = _make_ctx(guild, me, rc_alice)
    asyncio.run(cog.buy.callback(cog, ctx, "firework", 2))
    assert economy_db.get_economy_channel_balance(gid, rc_alice.id) == 500 - fw["price"] * 2
    inv = economy_db.get_inventory_channel(gid, rc_alice.id)
    assert inv and inv[0]["quantity"] == 2
    assert any("Purchase successful" in s for s in ctx.sent)


def test_buy_unknown_item_rejected(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 725
    guild, rc, houses, alive, me, bob, rc_alice, rc_bob, house1, cog = _build_world(gid)
    asyncio.run(cog._ensure_default_items(guild))
    ctx = _make_ctx(guild, me, rc_alice)
    asyncio.run(cog.buy.callback(cog, ctx, "nope", 1))
    assert any("Item not found" in s for s in ctx.sent)


def test_sell_sells_exactly_one_unit_and_refunds_half(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 726
    guild, rc, houses, alive, me, bob, rc_alice, rc_bob, house1, cog = _build_world(gid)
    asyncio.run(cog._ensure_default_items(guild))
    fw = economy_db.get_shop_item_by_name(gid, "firework")
    economy_db.set_economy_channel_balance(gid, rc_alice.id, 1000)
    economy_db.add_inventory_item_channel(gid, rc_alice.id, fw["id"], 3)
    ctx = _make_ctx(guild, me, rc_alice)
    asyncio.run(cog.sell_item.callback(cog, ctx, item_name="firework"))
    assert economy_db.get_inventory_channel(gid, rc_alice.id)[0]["quantity"] == 2
    assert economy_db.get_economy_channel_balance(gid, rc_alice.id) == 1000 + fw["price"] // 2
    ctx2 = _make_ctx(guild, me, rc_alice)
    asyncio.run(cog.sell_item.callback(cog, ctx2, item_name="nope"))
    assert any("not found" in s.lower() for s in ctx2.sent)


def test_sell_item_not_owned_rejected(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 727
    guild, rc, houses, alive, me, bob, rc_alice, rc_bob, house1, cog = _build_world(gid)
    asyncio.run(cog._ensure_default_items(guild))
    ctx = _make_ctx(guild, me, rc_alice)
    asyncio.run(cog.sell_item.callback(cog, ctx, item_name="firework"))
    assert any("don't own" in s.lower() for s in ctx.sent)


def test_additemrole_grants_items_to_role_members(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 728
    guild, rc, houses, alive, me, bob, rc_alice, rc_bob, house1, cog = _build_world(gid)
    asyncio.run(cog._ensure_default_items(guild))
    broom = economy_db.get_shop_item_by_name(gid, "broom")
    fw = economy_db.get_shop_item_by_name(gid, "firework")
    ctx = _make_ctx(guild, me, rc_alice)
    asyncio.run(cog.additemrole.callback(cog, ctx, alive, items_str="broom 3, firework 2"))
    for rc_ch in (rc_alice, rc_bob):
        m = {i["item_id"]: i["quantity"] for i in economy_db.get_inventory_channel(gid, rc_ch.id)}
        assert m.get(broom["id"]) == 3
        assert m.get(fw["id"]) == 2


def test_additemrole_rejects_non_positive_quantity(tmp_path, monkeypatch):
    """Negative or zero quantities are rejected instead of silently removing
    items from every role member's inventory."""
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 729
    guild, rc, houses, alive, me, bob, rc_alice, rc_bob, house1, cog = _build_world(gid)
    asyncio.run(cog._ensure_default_items(guild))
    broom = economy_db.get_shop_item_by_name(gid, "broom")
    economy_db.add_inventory_item_channel(gid, rc_alice.id, broom["id"], 5)
    ctx = _make_ctx(guild, me, rc_alice)
    asyncio.run(cog.additemrole.callback(cog, ctx, alive, items_str="broom -3"))
    assert economy_db.get_inventory_channel(gid, rc_alice.id)[0]["quantity"] == 5
    assert any("greater than 0" in s for s in ctx.sent)


def test_additemrole_invalid_pair_skipped(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 730
    guild, rc, houses, alive, me, bob, rc_alice, rc_bob, house1, cog = _build_world(gid)
    asyncio.run(cog._ensure_default_items(guild))
    ctx = _make_ctx(guild, me, rc_alice)
    asyncio.run(cog.additemrole.callback(cog, ctx, alive, items_str="broom-notright"))
    assert any("Invalid pair" in s for s in ctx.sent)
    assert economy_db.get_inventory_channel(gid, rc_alice.id) == []


def test_removeitem_removes_qty_and_rejects_zero(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 731
    guild, rc, houses, alive, me, bob, rc_alice, rc_bob, house1, cog = _build_world(gid)
    asyncio.run(cog._ensure_default_items(guild))
    broom = economy_db.get_shop_item_by_name(gid, "broom")
    economy_db.add_inventory_item_channel(gid, rc_bob.id, broom["id"], 3)
    ctx = _make_ctx(guild, me, rc_alice)
    asyncio.run(cog.removeitem.callback(cog, ctx, rc_bob, "broom", 1))
    assert economy_db.add_inventory_item_channel(gid, rc_bob.id, broom["id"], 0) == 2
    ctx2 = _make_ctx(guild, me, rc_alice)
    asyncio.run(cog.removeitem.callback(cog, ctx2, rc_bob, "broom", 0))
    assert any("positive" in s.lower() for s in ctx2.sent)


def test_use_generic_consumes_one(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 732
    guild, rc, houses, alive, me, bob, rc_alice, rc_bob, house1, cog = _build_world(gid)
    economy_db.add_shop_item(gid, "Plainthing", "", 5, is_default=False)
    pl = economy_db.get_shop_item_by_name(gid, "plainthing")
    economy_db.add_inventory_item_channel(gid, rc_alice.id, pl["id"], 1)
    ctx = _make_ctx(guild, me, rc_alice)
    asyncio.run(cog.use_item.callback(cog, ctx, item_name="plainthing"))
    assert economy_db.add_inventory_item_channel(gid, rc_alice.id, pl["id"], 0) == 0
    assert any("Used" in s for s in ctx.sent)


def test_use_consumes_only_when_effect_succeeds(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 733
    guild, rc, houses, alive, me, bob, rc_alice, rc_bob, house1, cog = _build_world(gid)
    asyncio.run(cog._ensure_default_items(guild))
    fw = economy_db.get_shop_item_by_name(gid, "firework")
    economy_db.add_inventory_item_channel(gid, rc_alice.id, fw["id"], 3)

    async def fail_effect(ctx):
        return False
    async def ok_effect(ctx):
        return True
    cog._trigger_fireworks = fail_effect
    ctx = _make_ctx(guild, me, rc_alice)
    asyncio.run(cog.use_item.callback(cog, ctx, item_name="firework"))
    assert economy_db.add_inventory_item_channel(gid, rc_alice.id, fw["id"], 0) == 3

    cog._trigger_fireworks = ok_effect
    ctx2 = _make_ctx(guild, me, rc_alice)
    asyncio.run(cog.use_item.callback(cog, ctx2, item_name="firework"))
    assert economy_db.add_inventory_item_channel(gid, rc_alice.id, fw["id"], 0) == 2


def test_give_transfers_between_rolechats(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 734
    guild, rc, houses, alive, me, bob, rc_alice, rc_bob, house1, cog = _build_world(gid)
    economy_db.set_economy_channel_balance(gid, rc_alice.id, 1000)
    ctx = _make_ctx(guild, me, house1)
    asyncio.run(cog.give.callback(cog, ctx, bob, "300"))
    assert economy_db.get_economy_channel_balance(gid, rc_alice.id) == 700
    assert economy_db.get_economy_channel_balance(gid, rc_bob.id) == 300


def test_give_all_transfers_everything(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 735
    guild, rc, houses, alive, me, bob, rc_alice, rc_bob, house1, cog = _build_world(gid)
    economy_db.set_economy_channel_balance(gid, rc_alice.id, 1000)
    ctx = _make_ctx(guild, me, house1)
    asyncio.run(cog.give.callback(cog, ctx, bob, "all"))
    assert economy_db.get_economy_channel_balance(gid, rc_alice.id) == 0
    assert economy_db.get_economy_channel_balance(gid, rc_bob.id) == 1000


def test_give_insufficient_rejected(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 736
    guild, rc, houses, alive, me, bob, rc_alice, rc_bob, house1, cog = _build_world(gid)
    economy_db.set_economy_channel_balance(gid, rc_alice.id, 100)
    ctx = _make_ctx(guild, me, house1)
    asyncio.run(cog.give.callback(cog, ctx, bob, "999999"))
    assert any("Insufficient" in s for s in ctx.sent)
    assert economy_db.get_economy_channel_balance(gid, rc_bob.id) == 0


def test_give_rejects_invalid_amount(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 737
    guild, rc, houses, alive, me, bob, rc_alice, rc_bob, house1, cog = _build_world(gid)
    ctx = _make_ctx(guild, me, house1)
    asyncio.run(cog.give.callback(cog, ctx, bob, "abc"))
    assert any("number or `all`" in s for s in ctx.sent)
    ctx2 = _make_ctx(guild, me, house1)
    asyncio.run(cog.give.callback(cog, ctx2, bob, "0"))
    assert any("greater than 0" in s for s in ctx2.sent)


def test_give_blocks_same_rolechat(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 738
    guild = _Guild(gid)
    rc = guild.cat("ROLES")
    houses = guild.cat("HOUSES")
    alive = guild.role("Alive")
    me = _User(1, "Alice", roles=[alive])
    bob = _User(2, "Bob", roles=[alive])
    rc_ch = guild.ch(101, "rc", category=rc, members=[me, bob])
    house1 = guild.ch(201, "house-1", category=houses, members=[me, bob])
    guild.members = [me, bob]
    alive.members = [me, bob]
    _setup_guild_data(gid)
    cog = economy_cog.Economy(bot=SimpleNamespace())
    economy_db.set_economy_channel_balance(gid, rc_ch.id, 500)
    ctx = _make_ctx(guild, me, house1)
    asyncio.run(cog.give.callback(cog, ctx, bob, "100"))
    assert any("same rolechat" in s for s in ctx.sent)
    assert economy_db.get_economy_channel_balance(gid, rc_ch.id) == 500


def test_give_money_transfers_wallet(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 739
    guild, rc, houses, alive, me, bob, rc_alice, rc_bob, house1, cog = _build_world(gid)
    economy_db.update_economy_balance(gid, 1, delta_wallet=500)
    ctx = _make_ctx(guild, me, rc_alice)
    asyncio.run(cog.give_money.callback(cog, ctx, bob, 200))
    assert economy_db.get_economy_account(gid, 1) == (300, 0)
    assert economy_db.get_economy_account(gid, 2) == (200, 0)


def test_give_money_rejects_non_positive_and_insufficient(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 740
    guild, rc, houses, alive, me, bob, rc_alice, rc_bob, house1, cog = _build_world(gid)
    ctx = _make_ctx(guild, me, rc_alice)
    asyncio.run(cog.give_money.callback(cog, ctx, bob, 0))
    assert any("greater than 0" in s for s in ctx.sent)
    economy_db.update_economy_balance(gid, 1, delta_wallet=10)
    ctx2 = _make_ctx(guild, me, rc_alice)
    asyncio.run(cog.give_money.callback(cog, ctx2, bob, 100))
    assert any("Insufficient" in s for s in ctx2.sent)
    assert economy_db.get_economy_account(gid, 1) == (10, 0)


def test_setcollect_validates_and_persists(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 741
    guild, rc, houses, alive, me, bob, rc_alice, rc_bob, house1, cog = _build_world(gid)
    ctx = _make_ctx(guild, me, rc_alice)
    asyncio.run(cog.setcollect.callback(cog, ctx, -5))
    assert any(">= 0" in s for s in ctx.sent)
    ctx2 = _make_ctx(guild, me, rc_alice)
    asyncio.run(cog.setcollect.callback(cog, ctx2, 999999))
    assert any("exceed" in s.lower() for s in ctx2.sent)
    ctx3 = _make_ctx(guild, me, rc_alice)
    asyncio.run(cog.setcollect.callback(cog, ctx3, 500))
    assert load_guild_data(gid).get("economy_collect_amount") == 500


def test_collect_adds_to_all_rolechats(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 742
    guild, rc, houses, alive, me, bob, rc_alice, rc_bob, house1, cog = _build_world(gid)
    ctx = _make_ctx(guild, me, rc_alice)
    asyncio.run(cog.collect.callback(cog, ctx))
    assert economy_db.get_economy_channel_balance(gid, rc_alice.id) == 100
    assert economy_db.get_economy_channel_balance(gid, rc_bob.id) == 100


def test_reseteconomy_with_confirm(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 743
    guild, rc, houses, alive, me, bob, rc_alice, rc_bob, house1, cog = _build_world(gid)
    economy_db.set_economy_channel_balance(gid, rc_alice.id, 9999)
    economy_db.set_economy_channel_balance(gid, rc_bob.id, 9999)

    async def fake_wait(self):
        self.confirmed = True
    monkeypatch.setattr(economy_cog.ConfirmView, "wait", fake_wait)
    ctx = _make_ctx(guild, me, rc_alice)
    asyncio.run(cog.reset_economy.callback(cog, ctx, 100))
    assert economy_db.get_economy_channel_balance(gid, rc_alice.id) == 100
    assert economy_db.get_economy_channel_balance(gid, rc_bob.id) == 100


def test_reseteconomy_aborted_when_not_confirmed(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 744
    guild, rc, houses, alive, me, bob, rc_alice, rc_bob, house1, cog = _build_world(gid)
    economy_db.set_economy_channel_balance(gid, rc_alice.id, 9999)

    async def fake_wait(self):
        self.confirmed = False
    monkeypatch.setattr(economy_cog.ConfirmView, "wait", fake_wait)
    ctx = _make_ctx(guild, me, rc_alice)
    asyncio.run(cog.reset_economy.callback(cog, ctx, 100))
    assert economy_db.get_economy_channel_balance(gid, rc_alice.id) == 9999


def test_reseteconomy_rejects_out_of_range(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 745
    guild, rc, houses, alive, me, bob, rc_alice, rc_bob, house1, cog = _build_world(gid)
    ctx = _make_ctx(guild, me, rc_alice)
    asyncio.run(cog.reset_economy.callback(cog, ctx, -1))
    assert any(">= 0" in s for s in ctx.sent)
    ctx2 = _make_ctx(guild, me, rc_alice)
    asyncio.run(cog.reset_economy.callback(cog, ctx2, 999999))
    assert any("10,000" in s for s in ctx2.sent)


def test_clearinventory_with_confirm(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 746
    guild, rc, houses, alive, me, bob, rc_alice, rc_bob, house1, cog = _build_world(gid)
    asyncio.run(cog._ensure_default_items(guild))
    fw = economy_db.get_shop_item_by_name(gid, "firework")
    economy_db.add_inventory_item_channel(gid, rc_alice.id, fw["id"], 2)
    economy_db.add_inventory_item_channel(gid, rc_bob.id, fw["id"], 1)

    async def fake_wait(self):
        self.confirmed = True
    monkeypatch.setattr(economy_cog.ConfirmView, "wait", fake_wait)
    ctx = _make_ctx(guild, me, rc_alice)
    asyncio.run(cog.clear_inventory.callback(cog, ctx))
    assert economy_db.get_inventory_channel(gid, rc_alice.id) == []
    assert economy_db.get_inventory_channel(gid, rc_bob.id) == []


def test_addmoney_and_removemoney_behavior(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 747
    guild, rc, houses, alive, me, bob, rc_alice, rc_bob, house1, cog = _build_world(gid)
    ctx = _make_ctx(guild, me, rc_alice)
    asyncio.run(cog.addmoney.callback(cog, ctx, rc_alice, 0))
    assert any("greater than 0" in s for s in ctx.sent)
    economy_db.set_economy_channel_balance(gid, rc_alice.id, 0)
    ctx2 = _make_ctx(guild, me, rc_alice)
    asyncio.run(cog.addmoney.callback(cog, ctx2, rc_alice, 50))
    assert economy_db.get_economy_channel_balance(gid, rc_alice.id) == 50
    ctx3 = _make_ctx(guild, me, rc_alice)
    asyncio.run(cog.removemoney.callback(cog, ctx3, rc_alice, 20))
    assert economy_db.get_economy_channel_balance(gid, rc_alice.id) == 30
    ctx4 = _make_ctx(guild, me, rc_alice)
    asyncio.run(cog.removemoney.callback(cog, ctx4, rc_alice, 999999))
    assert economy_db.get_economy_channel_balance(gid, rc_alice.id) == 0


def test_balance_command_in_rolechat(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 748
    guild, rc, houses, alive, me, bob, rc_alice, rc_bob, house1, cog = _build_world(gid)
    economy_db.set_economy_channel_balance(gid, rc_alice.id, 123)
    ctx = _make_ctx(guild, me, rc_alice)
    asyncio.run(cog.balance.callback(cog, ctx, None))
    assert any("123" in (e.description or "") for e in ctx.embeds)


def test_balance_blocked_outside_rolechat(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 749
    guild, rc, houses, alive, me, bob, rc_alice, rc_bob, house1, cog = _build_world(gid)
    ctx = _make_ctx(guild, me, house1)
    asyncio.run(cog.balance.callback(cog, ctx, None))
    assert any("RoleChats category" in s for s in ctx.sent)


def test_leaderboard_zeroes_deleted_channel_balances(tmp_path, monkeypatch):
    """Running .leaderboard zeroes balances of channels that no longer exist."""
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 750
    guild, rc, houses, alive, me, bob, rc_alice, rc_bob, house1, cog = _build_world(gid)
    economy_db.set_economy_channel_balance(gid, rc_alice.id, 50)
    economy_db.set_economy_channel_balance(gid, rc_bob.id, 300)
    economy_db.set_economy_channel_balance(gid, 9999, 500)
    ctx = _make_ctx(guild, me, rc_alice)
    asyncio.run(cog.leaderboard.callback(cog, ctx))
    assert economy_db.get_economy_channel_balance(gid, 9999) == 0
    assert any("300" in (e.description or "") for e in ctx.embeds)


def test_inventory_command_lists_items_in_rolechat(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 751
    guild, rc, houses, alive, me, bob, rc_alice, rc_bob, house1, cog = _build_world(gid)
    asyncio.run(cog._ensure_default_items(guild))
    fw = economy_db.get_shop_item_by_name(gid, "firework")
    economy_db.add_inventory_item_channel(gid, rc_alice.id, fw["id"], 2)
    ctx = _make_ctx(guild, me, rc_alice)
    asyncio.run(cog.inventory.callback(cog, ctx, None))
    assert any("🎒 Inventory" in s for s in ctx.sent)
    ctx2 = _make_ctx(guild, me, house1)
    asyncio.run(cog.inventory.callback(cog, ctx2, None))
    assert any("RoleChats category" in s for s in ctx2.sent)


# ------------------------------------------------------------------ #
# Shop / Inventory UI tests (stale state, permissions, modal, limits)
# ------------------------------------------------------------------ #

def test_shopview_buy_blocked_for_non_invoker(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 752
    guild = _Guild(gid)
    rc = guild.cat("ROLES")
    ch = guild.ch(1, "rc", category=rc)
    iid = economy_db.add_shop_item(gid, "Fumo", "", 50, is_default=False)
    items = economy_db.get_shop_items(gid)
    invoker = SimpleNamespace(id=55, guild_permissions=SimpleNamespace(administrator=True))
    other = SimpleNamespace(id=99, guild_permissions=SimpleNamespace(administrator=False))

    async def run():
        view = economy_cog.ShopView(["P"], [items], invoker, gid, ch.id)
        view.selected_item_id = iid
        i = _make_interaction(guild, other, ch)
        await view.btn_buy.callback.callback(view, i, None)
        return i

    i = asyncio.run(run())
    assert i.response.sent and "Not your menu" in i.response.sent[-1]
    assert economy_db.get_economy_channel_balance(gid, ch.id) == 0


def test_shopview_edit_price_rejected_for_stale_item(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 753
    guild = _Guild(gid)
    rc = guild.cat("ROLES")
    ch = guild.ch(1, "rc", category=rc)
    economy_db.add_shop_item(gid, "Fumo", "", 50, is_default=False)
    items = economy_db.get_shop_items(gid)
    deleted_id = items[0]["id"]
    economy_db.remove_shop_item(gid, deleted_id)
    invoker = SimpleNamespace(id=55, guild_permissions=SimpleNamespace(administrator=True))

    async def run():
        view = economy_cog.ShopView(["P"], [items], invoker, gid, ch.id)
        view.selected_item_id = deleted_id
        i = _make_interaction(guild, invoker, ch)
        await view.btn_edit_price.callback.callback(view, i, None)
        return i

    i = asyncio.run(run())
    assert i.response.sent and "not found" in i.response.sent[-1]


def test_edit_price_modal_rejects_invalid_values(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 754
    iid = economy_db.add_shop_item(gid, "Fumo", "", 50, is_default=False)
    item = next(i for i in economy_db.get_shop_items(gid) if i["id"] == iid)
    guild = _Guild(gid)
    ch = guild.ch(1, "rc", category=guild.cat("ROLES"))
    user = SimpleNamespace(id=1)

    async def run(value):
        modal = economy_cog.EditPriceModal(gid, item)
        modal.price_input = SimpleNamespace(value=value)
        i = _make_interaction(guild, user, ch)
        await modal.on_submit(i)
        return i

    i = asyncio.run(run("notanum"))
    assert i.response.sent and "number" in i.response.sent[-1]
    i2 = asyncio.run(run("-5"))
    assert i2.response.sent and "0" in i2.response.sent[-1]
    assert next(x for x in economy_db.get_shop_items(gid) if x["id"] == iid)["price"] == 50


def test_inventoryview_use_blocked_for_deleted_item(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 755
    guild = _Guild(gid)
    rc = guild.cat("ROLES")
    ch = guild.ch(1, "rc", category=rc)
    iid = economy_db.add_shop_item(gid, "Perish", "", 10, is_default=False)
    economy_db.add_inventory_item_channel(gid, ch.id, iid, 1)
    inv_items = economy_db.get_inventory_channel(gid, ch.id)
    economy_db.remove_shop_item(gid, iid)
    invoker = SimpleNamespace(id=55)

    async def run():
        view = economy_cog.InventoryView(inv_items, invoker, ch.id, economy_cog.Economy(bot=MagicMock()))
        view.selected_item_id = iid
        i = _make_interaction(guild, invoker, ch)
        await view.btn_use.callback.callback(view, i, None)
        return i

    i = asyncio.run(run())
    assert i.response.sent and "no longer" in i.response.sent[-1]


def test_inventoryview_sell_blocked_for_deleted_item(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 756
    guild = _Guild(gid)
    rc = guild.cat("ROLES")
    ch = guild.ch(1, "rc", category=rc)
    iid = economy_db.add_shop_item(gid, "Perish", "", 10, is_default=False)
    economy_db.add_inventory_item_channel(gid, ch.id, iid, 1)
    inv_items = economy_db.get_inventory_channel(gid, ch.id)
    economy_db.remove_shop_item(gid, iid)
    invoker = SimpleNamespace(id=55)

    async def run():
        view = economy_cog.InventoryView(inv_items, invoker, ch.id, economy_cog.Economy(bot=MagicMock()))
        view.selected_item_id = iid
        i = _make_interaction(guild, invoker, ch)
        await view.btn_sell.callback.callback(view, i, None)
        return i

    i = asyncio.run(run())
    assert i.response.sent and ("no longer" in i.response.sent[-1] or "price" in i.response.sent[-1])


def test_shop_select_label_exceeds_discord_limit_for_long_item_names(tmp_path, monkeypatch):
    """Documents a latent UI bug: .additem permits 300-char names, but
    ShopItemSelect builds option labels without truncation (Discord limit 100),
    so .shop fails to render when such an item exists."""
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 757
    economy_db.add_shop_item(gid, "L" * 300, "", 10, is_default=False)
    items = economy_db.get_shop_items(gid)
    sel = economy_cog.ShopItemSelect(items, 0)
    assert len(sel.options[0].label) > 100


def test_edit_price_modal_title_exceeds_discord_limit_for_long_item_names(tmp_path, monkeypatch):
    """Documents a latent UI bug: EditPriceModal builds its title from the item
    name without truncation (Discord modal-title limit 45)."""
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 758
    economy_db.add_shop_item(gid, "L" * 300, "", 10, is_default=False)
    item = economy_db.get_shop_items(gid)[0]

    async def run():
        return economy_cog.EditPriceModal(gid, item)

    modal = asyncio.run(run())
    assert len(modal.title) > 45


def test_inventory_select_label_truncated_to_discord_limit(tmp_path, monkeypatch):
    economy_db = _fresh_economy_db(tmp_path, monkeypatch)
    gid = 759
    economy_db.add_shop_item(gid, "L" * 300, "D" * 300, 10, is_default=False)
    iid = economy_db.get_shop_items(gid)[0]["id"]
    inv_items = [{"item_id": iid, "name": "L" * 300, "description": "D" * 300, "quantity": 9}]
    sel = economy_cog.InventoryUseSelect(inv_items)
    assert len(sel.options[0].label) <= 100
    assert len(sel.options[0].description) <= 100


def test_whisper_select_labels_truncated_to_discord_limit():
    src = inspect.getsource(economy_cog.Economy._trigger_whisper)
    assert "display_name[:95]" in src
    src2 = inspect.getsource(economy_cog.InventoryView._do_whisper)
    assert "display_name[:95]" in src2


# ------------------------------------------------------------------ #
# Structural: permission decorators + command/UI location parity
# ------------------------------------------------------------------ #

def test_admin_commands_have_permission_checks():
    for name in ("additem", "edititem", "delitem", "additemrole", "removeitem",
                 "reset_economy", "clear_inventory", "addmoney", "removemoney",
                 "add_money_role", "setcollect", "collect", "leaderboard"):
        assert len(getattr(economy_cog.Economy, name).checks) > 0, name


def test_player_commands_have_no_permission_checks():
    for name in ("use_item", "buy", "inventory", "sell_item", "give_money",
                 "give", "balance", "shop"):
        assert len(getattr(economy_cog.Economy, name).checks) == 0, name


def test_use_command_restricts_location_by_item_type():
    src = inspect.getsource(economy_cog.Economy.use_item.callback)
    assert "_is_houses_category" in src and "_is_rolechat_category" in src


def test_inventory_command_requires_rolechat_category():
    src = inspect.getsource(economy_cog.Economy.inventory.callback)
    assert "RoleChats category" in src


def test_buy_and_sell_commands_require_rolechat_category():
    src = inspect.getsource(economy_cog.Economy.buy.callback)
    assert "_is_rolechat_category" in src
    src2 = inspect.getsource(economy_cog.Economy.sell_item.callback)
    assert "_is_rolechat_category" in src2
