"""Tests for Lists cog (auto-generated by testing framework)."""

import asyncio
import pytest
from unittest.mock import MagicMock, AsyncMock, patch
import discord

from cogs import lists_cog
from cogs.lists_cog import _resolve_player_name


def _run(coro):
    loop = asyncio.new_event_loop()
    try:
        return loop.run_until_complete(coro)
    finally:
        loop.close()


class TestLists:
    """Validate all commands exist and have required metadata."""

    def test_playerlist_exists(self):
        """Verify playerlist command exists on the cog."""
        assert hasattr(lists_cog.Lists, 'playerlist')

    def test_playerlist_has_help(self):
        """Verify playerlist command has help text."""
        method = getattr(lists_cog.Lists, 'playerlist')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_sponsorlist_exists(self):
        """Verify sponsorlist command exists on the cog."""
        assert hasattr(lists_cog.Lists, 'sponsorlist')

    def test_sponsorlist_has_help(self):
        """Verify sponsorlist command has help text."""
        method = getattr(lists_cog.Lists, 'sponsorlist')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_setuphouselist_exists(self):
        """Verify setuphouselist command exists on the cog."""
        assert hasattr(lists_cog.Lists, 'setuphouselist')

    def test_setuphouselist_has_help(self):
        """Verify setuphouselist command has help text."""
        method = getattr(lists_cog.Lists, 'setuphouselist')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_houselistadd_exists(self):
        """Verify houselistadd command exists on the cog."""
        assert hasattr(lists_cog.Lists, 'houselistadd')

    def test_houselistadd_has_help(self):
        """Verify houselistadd command has help text."""
        method = getattr(lists_cog.Lists, 'houselistadd')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_houselistremove_exists(self):
        """Verify houselistremove command exists on the cog."""
        assert hasattr(lists_cog.Lists, 'houselistremove')

    def test_houselistremove_has_help(self):
        """Verify houselistremove command has help text."""
        method = getattr(lists_cog.Lists, 'houselistremove')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_houselist_exists(self):
        """Verify houselist command exists on the cog."""
        assert hasattr(lists_cog.Lists, 'houselist')

    def test_houselist_has_help(self):
        """Verify houselist command has help text."""
        method = getattr(lists_cog.Lists, 'houselist')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_deadlist_exists(self):
        """Verify deadlist command exists on the cog."""
        assert hasattr(lists_cog.Lists, 'deadlist')

    def test_deadlist_has_help(self):
        """Verify deadlist command has help text."""
        method = getattr(lists_cog.Lists, 'deadlist')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0

    def test_map_command_exists(self):
        """Verify map_command command exists on the cog."""
        assert hasattr(lists_cog.Lists, 'map_command')

    def test_map_command_has_help(self):
        """Verify map_command command has help text."""
        method = getattr(lists_cog.Lists, 'map_command')
        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)
        assert doc is not None and len(doc.strip()) > 0


class TestResolvePlayerName:
    """Deep tests for _resolve_player_name helper."""

    def _make_ctx(self, member=None, member_id=None):
        guild = MagicMock()
        if member_id is not None and member is not None:
            guild.get_member.side_effect = lambda mid: member if mid == member_id else None
        elif member is not None:
            guild.get_member.return_value = member
        else:
            guild.get_member.return_value = None
        ctx = MagicMock()
        ctx.guild = guild
        return ctx

    def test_mention_resolves_to_display_name(self):
        """<@id> mention resolves to member display_name."""
        member = MagicMock()
        member.display_name = "JohnDoe"
        ctx = self._make_ctx(member, 123456)

        result = _resolve_player_name(ctx, "<@123456>")
        assert result == "JohnDoe"
        ctx.guild.get_member.assert_called_with(123456)

    def test_nickname_mention_resolves(self):
        """<@!id> nickname mention resolves to member display_name."""
        member = MagicMock()
        member.display_name = "NickName"
        ctx = self._make_ctx(member, 123456)

        result = _resolve_player_name(ctx, "<@!123456>")
        assert result == "NickName"
        ctx.guild.get_member.assert_called_with(123456)

    def test_raw_id_resolves_to_display_name(self):
        """Raw numeric string ID resolves to member display_name."""
        member = MagicMock()
        member.display_name = "JaneSmith"
        ctx = self._make_ctx(member, 123456)

        result = _resolve_player_name(ctx, "123456")
        assert result == "JaneSmith"

    def test_large_snowflake_id_resolves(self):
        """Large Discord snowflake IDs (18+ digits) resolve correctly."""
        member = MagicMock()
        member.display_name = "SnowflakeUser"
        big_id = 123456789012345678
        ctx = self._make_ctx(member, big_id)

        result = _resolve_player_name(ctx, str(big_id))
        assert result == "SnowflakeUser"
        ctx.guild.get_member.assert_called_with(big_id)

    def test_nonexistent_id_falls_through(self):
        """Numeric ID that doesn't match any member returns the raw string."""
        ctx = self._make_ctx(None)

        result = _resolve_player_name(ctx, "9999999999")
        assert result == "9999999999"

    def test_plain_text_passes_through(self):
        """Plain text name is returned as-is."""
        ctx = self._make_ctx(None)

        result = _resolve_player_name(ctx, "JohnDoe")
        assert result == "JohnDoe"

    def test_plain_text_with_spaces(self):
        """Plain text with spaces passes through unchanged."""
        ctx = self._make_ctx(None)

        result = _resolve_player_name(ctx, "First Last")
        assert result == "First Last"

    def test_none_input_returns_none(self):
        """None input returns None."""
        result = _resolve_player_name(MagicMock(), None)
        assert result is None

    def test_empty_string_passes_through(self):
        """Empty string is returned as-is."""
        result = _resolve_player_name(MagicMock(), "")
        assert result == ""

    def test_whitespace_only_passes_through(self):
        """Whitespace-only string is returned as-is (strip leaves empty, int() fails)."""
        result = _resolve_player_name(MagicMock(), "   ")
        assert result == "   "

    def test_mention_with_surrounding_text(self):
        """Partial mention with surrounding text is NOT stripped (only pure mentions)."""
        ctx = self._make_ctx(None)
        result = _resolve_player_name(ctx, "hey <@123456> bye")
        assert result == "hey <@123456> bye"

    def test_malformed_mention_at_end(self):
        """Truncated mention <@ is returned as-is."""
        ctx = self._make_ctx(None)
        result = _resolve_player_name(ctx, "<@")
        assert result == "<@"

    def test_user_object_mention_format(self):
        """<@id> with Discord user object format resolves correctly."""
        member = MagicMock()
        member.display_name = "RealName"
        ctx = self._make_ctx(member, 321117543378976771)

        result = _resolve_player_name(ctx, "<@321117543378976771>")
        assert result == "RealName"

    def test_id_string_not_in_guild(self):
        """Numeric ID that doesn't match a member in the guild falls through."""
        guild = MagicMock()
        guild.get_member.return_value = None
        ctx = MagicMock()
        ctx.guild = guild

        result = _resolve_player_name(ctx, "111222333444555666")
        assert result == "111222333444555666"

    def test_display_name_preserved_not_username(self):
        """Resolved name uses display_name, not name or global_name."""
        member = MagicMock()
        member.display_name = "CoolNickname"
        member.name = "username123"
        member.global_name = "GlobalName"
        ctx = self._make_ctx(member, 42)

        result = _resolve_player_name(ctx, "42")
        assert result == "CoolNickname"


class TestDeadlistRemoveFlow:
    """Deep tests for the .deadlist remove command flow."""

    def _make_ctx(self, admin=True, member=None):
        ctx = MagicMock()
        ctx.author.guild_permissions.administrator = admin
        guild = MagicMock()
        if member is not None:
            guild.get_member.side_effect = lambda mid: member if mid == getattr(member, '_test_id', None) else None
        else:
            guild.get_member.return_value = None
        ctx.guild = guild
        ctx.send = AsyncMock()
        return ctx

    def test_remove_requires_admin(self):
        """Non-admin user is rejected."""
        cog = lists_cog.Lists(None)
        ctx = self._make_ctx(admin=False)

        _run(cog.deadlist.callback(cog, ctx, "remove", "JohnDoe"))
        ctx.send.assert_called_once()
        sent = str(ctx.send.call_args)
        assert "permissions" in sent.lower()

    def test_remove_no_player_specified(self):
        """No player argument shows 'No player specified'."""
        cog = lists_cog.Lists(None)
        ctx = self._make_ctx()

        _run(cog.deadlist.callback(cog, ctx, "remove"))
        ctx.send.assert_called_once()
        sent = str(ctx.send.call_args)
        assert "No player specified" in sent

    def test_remove_success_message(self):
        """Successful removal sends 'removed from Deadlist'."""
        cog = lists_cog.Lists(None)
        ctx = self._make_ctx()

        with patch('cogs.lists_cog.remove_player', return_value=1), \
             patch('cogs.lists_cog.load_guild_data', return_value=True):
            _run(cog.deadlist.callback(cog, ctx, "remove", "JohnDoe"))

        ctx.send.assert_called_once()
        sent = ctx.send.call_args[1].get("content", "") or str(ctx.send.call_args)
        assert "removed from Deadlist" in sent
        assert "JohnDoe" in sent

    def test_remove_not_found_message(self):
        """No match sends 'No deadlist entry found'."""
        cog = lists_cog.Lists(None)
        ctx = self._make_ctx()

        with patch('cogs.lists_cog.remove_player', return_value=0), \
             patch('cogs.lists_cog.load_guild_data', return_value=True):
            _run(cog.deadlist.callback(cog, ctx, "remove", "JohnDoe"))

        ctx.send.assert_called_once()
        sent = ctx.send.call_args[1].get("content", "") or str(ctx.send.call_args)
        assert "No deadlist entry" in sent
        assert "JohnDoe" in sent

    def test_remove_mention_resolves_before_delete(self):
        """@User mention is resolved to display_name before calling remove_player."""
        member = MagicMock()
        member.display_name = "JohnDoe"
        member._test_id = 123456
        cog = lists_cog.Lists(None)
        ctx = self._make_ctx(member=member)

        with patch('cogs.lists_cog.remove_player', return_value=1) as mock_rm, \
             patch('cogs.lists_cog.load_guild_data', return_value=True):
            _run(cog.deadlist.callback(cog, ctx, "remove", "<@123456>"))

        mock_rm.assert_called_once_with("JohnDoe", ctx.guild.id)

    def test_remove_nickname_mention_resolves(self):
        """<@!id> nickname mention resolves to display_name."""
        member = MagicMock()
        member.display_name = "NickName"
        member._test_id = 789012
        cog = lists_cog.Lists(None)
        ctx = self._make_ctx(member=member)

        with patch('cogs.lists_cog.remove_player', return_value=1) as mock_rm, \
             patch('cogs.lists_cog.load_guild_data', return_value=True):
            _run(cog.deadlist.callback(cog, ctx, "remove", "<@!789012>"))

        mock_rm.assert_called_once_with("NickName", ctx.guild.id)

    def test_remove_raw_id_resolves(self):
        """Raw numeric user ID resolves to display_name."""
        member = MagicMock()
        member.display_name = "JaneSmith"
        member._test_id = 321117543378976771
        cog = lists_cog.Lists(None)
        ctx = self._make_ctx(member=member)

        with patch('cogs.lists_cog.remove_player', return_value=1) as mock_rm, \
             patch('cogs.lists_cog.load_guild_data', return_value=True):
            _run(cog.deadlist.callback(cog, ctx, "remove", "321117543378976771"))

        mock_rm.assert_called_once_with("JaneSmith", ctx.guild.id)

    def test_remove_plain_name_passes_through(self):
        """Plain text name is used directly for removal."""
        cog = lists_cog.Lists(None)
        ctx = self._make_ctx()

        with patch('cogs.lists_cog.remove_player', return_value=1) as mock_rm, \
             patch('cogs.lists_cog.load_guild_data', return_value=True):
            _run(cog.deadlist.callback(cog, ctx, "remove", "JohnDoe"))

        mock_rm.assert_called_once_with("JohnDoe", ctx.guild.id)

    def test_remove_calls_with_correct_guild_id(self):
        """remove_player receives the guild's ID, not some other value."""
        cog = lists_cog.Lists(None)
        ctx = self._make_ctx()
        ctx.guild.id = 999999

        with patch('cogs.lists_cog.remove_player', return_value=1) as mock_rm, \
             patch('cogs.lists_cog.load_guild_data', return_value=True):
            _run(cog.deadlist.callback(cog, ctx, "remove", "Test"))

        mock_rm.assert_called_once_with("Test", 999999)

    def test_remove_duplicates_all_deleted(self):
        """When multiple rows exist, all are deleted and rowcount reflects that."""
        cog = lists_cog.Lists(None)
        ctx = self._make_ctx()

        with patch('cogs.lists_cog.remove_player', return_value=3) as mock_rm, \
             patch('cogs.lists_cog.load_guild_data', return_value=True):
            _run(cog.deadlist.callback(cog, ctx, "remove", "JohnDoe"))

        mock_rm.assert_called_once()
        ctx.send.assert_called_once()
        sent = ctx.send.call_args[1].get("content", "") or str(ctx.send.call_args)
        assert "removed from Deadlist" in sent

    def test_remove_no_side_effects_on_not_found(self):
        """When rowcount is 0, the bot does NOT claim removal succeeded."""
        cog = lists_cog.Lists(None)
        ctx = self._make_ctx()

        with patch('cogs.lists_cog.remove_player', return_value=0), \
             patch('cogs.lists_cog.load_guild_data', return_value=True):
            _run(cog.deadlist.callback(cog, ctx, "remove", "GhostPlayer"))

        ctx.send.assert_called_once()
        sent = ctx.send.call_args[1].get("content", "") or str(ctx.send.call_args)
        assert "removed from Deadlist" not in sent
        assert "No deadlist entry" in sent


class TestDeadlistEditFlow:
    """Deep tests for the .deadlist edit command flow."""

    def _make_ctx(self, admin=True, member=None):
        ctx = MagicMock()
        ctx.author.guild_permissions.administrator = admin
        guild = MagicMock()
        if member is not None:
            guild.get_member.side_effect = lambda mid: member if mid == getattr(member, '_test_id', None) else None
        else:
            guild.get_member.return_value = None
        ctx.guild = guild
        ctx.send = AsyncMock()
        return ctx

    def test_edit_requires_admin(self):
        """Non-admin user is rejected."""
        cog = lists_cog.Lists(None)
        ctx = self._make_ctx(admin=False)

        _run(cog.deadlist.callback(cog, ctx, "edit", "JohnDoe", "village", role="Doctor"))
        ctx.send.assert_called_once()
        sent = str(ctx.send.call_args)
        assert "permissions" in sent.lower()

    def test_edit_missing_args_shows_error(self):
        """Missing team/role shows fill-all-inputs error."""
        cog = lists_cog.Lists(None)
        ctx = self._make_ctx()

        _run(cog.deadlist.callback(cog, ctx, "edit", "JohnDoe"))
        ctx.send.assert_called_once()
        sent = str(ctx.send.call_args)
        assert "fill all inputs" in sent.lower()

    def test_edit_invalid_team_shows_error(self):
        """Invalid team name shows error."""
        cog = lists_cog.Lists(None)
        ctx = self._make_ctx()

        with patch('cogs.lists_cog.remove_player', return_value=1), \
             patch('cogs.lists_cog.load_guild_data', return_value=True):
            _run(cog.deadlist.callback(cog, ctx, "edit", "JohnDoe", "invalidteam", role="Doctor"))

        ctx.send.assert_called_once()
        sent = ctx.send.call_args[1].get("content", "") or str(ctx.send.call_args)
        assert "Invalid team" in sent

    def test_edit_removes_old_then_adds_new(self):
        """Edit calls remove_player then add_player with resolved name."""
        member = MagicMock()
        member.display_name = "JohnDoe"
        member._test_id = 42
        cog = lists_cog.Lists(None)
        ctx = self._make_ctx(member=member)

        with patch('cogs.lists_cog.remove_player', return_value=1) as mock_rm, \
             patch('cogs.lists_cog.add_player') as mock_add, \
             patch('cogs.lists_cog.load_guild_data', return_value=True):
            _run(cog.deadlist.callback(cog, ctx, "edit", "<@42>", "village", role="Doctor"))

        mock_rm.assert_called_once_with("JohnDoe", ctx.guild.id)
        mock_add.assert_called_once_with("JohnDoe", "village", "Doctor", ctx.guild.id)

    def test_edit_success_message(self):
        """Successful edit sends 'edited in deadlist'."""
        cog = lists_cog.Lists(None)
        ctx = self._make_ctx()

        with patch('cogs.lists_cog.remove_player', return_value=1), \
             patch('cogs.lists_cog.add_player'), \
             patch('cogs.lists_cog.load_guild_data', return_value=True):
            _run(cog.deadlist.callback(cog, ctx, "edit", "JohnDoe", "evil", role="Wolf"))

        ctx.send.assert_called_once()
        sent = ctx.send.call_args[1].get("content", "") or str(ctx.send.call_args)
        assert "edited in deadlist" in sent

    def test_edit_team_normalization_village(self):
        """Team aliases normalize to canonical names."""
        cog = lists_cog.Lists(None)
        ctx = self._make_ctx()

        for alias in ["vill", "village", "v", "good"]:
            with patch('cogs.lists_cog.remove_player', return_value=1), \
                 patch('cogs.lists_cog.add_player') as mock_add, \
                 patch('cogs.lists_cog.load_guild_data', return_value=True):
                _run(cog.deadlist.callback(cog, ctx, "edit", "X", alias, role="R"))
            assert mock_add.call_args[0][1] == "village", f"Alias '{alias}' should normalize to 'village'"

    def test_edit_team_normalization_evil(self):
        """Evil team aliases normalize correctly."""
        cog = lists_cog.Lists(None)
        ctx = self._make_ctx()

        for alias in ["evil", "e", "bad"]:
            with patch('cogs.lists_cog.remove_player', return_value=1), \
                 patch('cogs.lists_cog.add_player') as mock_add, \
                 patch('cogs.lists_cog.load_guild_data', return_value=True):
                _run(cog.deadlist.callback(cog, ctx, "edit", "X", alias, role="R"))
            assert mock_add.call_args[0][1] == "evil", f"Alias '{alias}' should normalize to 'evil'"

    def test_edit_team_normalization_neutral(self):
        """Neutral team aliases normalize correctly."""
        cog = lists_cog.Lists(None)
        ctx = self._make_ctx()

        for alias in ["neutral", "n", "solo", "s"]:
            with patch('cogs.lists_cog.remove_player', return_value=1), \
                 patch('cogs.lists_cog.add_player') as mock_add, \
                 patch('cogs.lists_cog.load_guild_data', return_value=True):
                _run(cog.deadlist.callback(cog, ctx, "edit", "X", alias, role="R"))
            assert mock_add.call_args[0][1] == "neutral", f"Alias '{alias}' should normalize to 'neutral'"

    def test_edit_team_normalization_rk(self):
        """RK team aliases normalize correctly."""
        cog = lists_cog.Lists(None)
        ctx = self._make_ctx()

        for alias in ["rk", "r", "lms"]:
            with patch('cogs.lists_cog.remove_player', return_value=1), \
                 patch('cogs.lists_cog.add_player') as mock_add, \
                 patch('cogs.lists_cog.load_guild_data', return_value=True):
                _run(cog.deadlist.callback(cog, ctx, "edit", "X", alias, role="R"))
            assert mock_add.call_args[0][1] == "rk", f"Alias '{alias}' should normalize to 'rk'"

    def test_edit_team_normalization_corrupted(self):
        """Corrupted team aliases normalize correctly."""
        cog = lists_cog.Lists(None)
        ctx = self._make_ctx()

        for alias in ["corrupted", "corr", "unk", "?", "???", "c"]:
            with patch('cogs.lists_cog.remove_player', return_value=1), \
                 patch('cogs.lists_cog.add_player') as mock_add, \
                 patch('cogs.lists_cog.load_guild_data', return_value=True):
                _run(cog.deadlist.callback(cog, ctx, "edit", "X", alias, role="R"))
            assert mock_add.call_args[0][1] == "corrupted", f"Alias '{alias}' should normalize to 'corrupted'"


class TestDeadlistAddFlow:
    """Deep tests for the .deadlist add command flow."""

    def _make_ctx(self, admin=True):
        ctx = MagicMock()
        ctx.author.guild_permissions.administrator = admin
        ctx.guild = MagicMock()
        ctx.guild.get_member.return_value = None
        ctx.send = AsyncMock()
        return ctx

    def test_add_requires_admin(self):
        """Non-admin user is rejected."""
        cog = lists_cog.Lists(None)
        ctx = self._make_ctx(admin=False)

        _run(cog.deadlist.callback(cog, ctx, "add", "JohnDoe", "village", role="Doctor"))
        ctx.send.assert_called_once()
        sent = str(ctx.send.call_args)
        assert "permissions" in sent.lower()

    def test_add_missing_args_shows_error(self):
        """Missing team/role shows add usage error."""
        cog = lists_cog.Lists(None)
        ctx = self._make_ctx()

        _run(cog.deadlist.callback(cog, ctx, "add", "JohnDoe"))
        ctx.send.assert_called_once()
        sent = str(ctx.send.call_args)
        assert "all three arguments are required" in sent.lower()
        assert "deadlist add" in sent.lower()

    def test_add_invalid_team_shows_error(self):
        """Invalid team name shows error."""
        cog = lists_cog.Lists(None)
        ctx = self._make_ctx()

        with patch('cogs.lists_cog.load_guild_data', return_value=True):
            _run(cog.deadlist.callback(cog, ctx, "add", "JohnDoe", "invalidteam", role="Doctor"))

        ctx.send.assert_called_once()
        sent = ctx.send.call_args[1].get("content", "") or str(ctx.send.call_args)
        assert "Invalid team" in sent

    def test_add_success_message(self):
        """Successful add sends 'added to Deadlist'."""
        cog = lists_cog.Lists(None)
        ctx = self._make_ctx()

        with patch('cogs.lists_cog.add_player') as mock_add, \
             patch('cogs.lists_cog.load_guild_data', return_value=True):
            _run(cog.deadlist.callback(cog, ctx, "add", "JohnDoe", "village", role="Doctor"))

        ctx.send.assert_called_once()
        sent = ctx.send.call_args[1].get("content", "") or str(ctx.send.call_args)
        assert "added to Deadlist" in sent

    def test_add_calls_add_player(self):
        """Add calls add_player with correct arguments."""
        cog = lists_cog.Lists(None)
        ctx = self._make_ctx()
        ctx.guild.id = 555555

        with patch('cogs.lists_cog.add_player') as mock_add, \
             patch('cogs.lists_cog.load_guild_data', return_value=True):
            _run(cog.deadlist.callback(cog, ctx, "add", "JohnDoe", "evil", role="Wolf"))

        mock_add.assert_called_once_with("JohnDoe", "evil", "Wolf", 555555)

    def test_add_team_normalization_village(self):
        """Village aliases normalize correctly."""
        cog = lists_cog.Lists(None)
        ctx = self._make_ctx()

        for alias in ["vill", "village", "v", "good"]:
            with patch('cogs.lists_cog.add_player') as mock_add, \
                 patch('cogs.lists_cog.load_guild_data', return_value=True):
                _run(cog.deadlist.callback(cog, ctx, "add", "X", alias, role="R"))
            assert mock_add.call_args[0][1] == "village", f"Alias '{alias}' should normalize to 'village'"

    def test_add_team_normalization_evil(self):
        """Evil aliases normalize correctly."""
        cog = lists_cog.Lists(None)
        ctx = self._make_ctx()

        for alias in ["evil", "e", "bad"]:
            with patch('cogs.lists_cog.add_player') as mock_add, \
                 patch('cogs.lists_cog.load_guild_data', return_value=True):
                _run(cog.deadlist.callback(cog, ctx, "add", "X", alias, role="R"))
            assert mock_add.call_args[0][1] == "evil", f"Alias '{alias}' should normalize to 'evil'"

    def test_add_team_normalization_neutral(self):
        """Neutral aliases normalize correctly."""
        cog = lists_cog.Lists(None)
        ctx = self._make_ctx()

        for alias in ["neutral", "n", "solo", "s"]:
            with patch('cogs.lists_cog.add_player') as mock_add, \
                 patch('cogs.lists_cog.load_guild_data', return_value=True):
                _run(cog.deadlist.callback(cog, ctx, "add", "X", alias, role="R"))
            assert mock_add.call_args[0][1] == "neutral", f"Alias '{alias}' should normalize to 'neutral'"

    def test_add_team_normalization_rk(self):
        """RK aliases normalize correctly."""
        cog = lists_cog.Lists(None)
        ctx = self._make_ctx()

        for alias in ["rk", "r", "lms"]:
            with patch('cogs.lists_cog.add_player') as mock_add, \
                 patch('cogs.lists_cog.load_guild_data', return_value=True):
                _run(cog.deadlist.callback(cog, ctx, "add", "X", alias, role="R"))
            assert mock_add.call_args[0][1] == "rk", f"Alias '{alias}' should normalize to 'rk'"

    def test_add_team_normalization_corrupted(self):
        """Corrupted aliases normalize correctly."""
        cog = lists_cog.Lists(None)
        ctx = self._make_ctx()

        for alias in ["corrupted", "corr", "unk", "?", "???", "c"]:
            with patch('cogs.lists_cog.add_player') as mock_add, \
                 patch('cogs.lists_cog.load_guild_data', return_value=True):
                _run(cog.deadlist.callback(cog, ctx, "add", "X", alias, role="R"))
            assert mock_add.call_args[0][1] == "corrupted", f"Alias '{alias}' should normalize to 'corrupted'"


class TestDeadlistDisplayFlow:
    """Deep tests for the .d display command."""

    def test_display_calls_get_team_players(self):
        """Display queries all 5 team types."""
        cog = lists_cog.Lists(None)
        ctx = MagicMock()
        ctx.guild.id = 111111
        ctx.send = AsyncMock()

        with patch('cogs.lists_cog.get_team_players', return_value=[]):
            _run(cog.deadlist.callback(cog, ctx))

        ctx.send.assert_called_once()

    def test_display_embed_has_title(self):
        """Display embed has 'Deadlist' title."""
        cog = lists_cog.Lists(None)
        ctx = MagicMock()
        ctx.guild.id = 111111
        ctx.send = AsyncMock()

        with patch('cogs.lists_cog.get_team_players', return_value=[]):
            _run(cog.deadlist.callback(cog, ctx))

        embed = ctx.send.call_args[1]["embed"]
        assert embed.title == "Deadlist"

    def test_display_shows_team_sections(self):
        """Players are grouped by team in the embed."""
        cog = lists_cog.Lists(None)
        ctx = MagicMock()
        ctx.guild.id = 111111
        ctx.send = AsyncMock()

        def mock_get(team, server):
            if team == "village":
                return [("Doctor", "Doctor")]
            elif team == "evil":
                return [("Wolf", "Werewolf")]
            return []

        with patch('cogs.lists_cog.get_team_players', side_effect=mock_get):
            _run(cog.deadlist.callback(cog, ctx))

        embed = ctx.send.call_args[1]["embed"]
        field_names = [f.name for f in embed.fields]
        assert any("Village" in n for n in field_names)
        assert any("Evil" in n for n in field_names)


class TestRemovePlayerRowcount:
    """Deep tests for remove_player returning correct rowcount."""

    def test_returns_integer(self):
        """remove_player returns an integer."""
        from cogs import data_utils
        with patch('cogs.data_utils._bot_db') as mock_db:
            mock_db.remove_player.return_value = 0
            result = data_utils.remove_player("X", 1)
            assert isinstance(result, int)

    def test_passes_through_return_value(self):
        """data_utils wrapper passes bot_db return value through."""
        from cogs import data_utils
        with patch('cogs.data_utils._bot_db') as mock_db:
            mock_db.remove_player.return_value = 5
            assert data_utils.remove_player("X", 1) == 5
        with patch('cogs.data_utils._bot_db') as mock_db:
            mock_db.remove_player.return_value = 0
            assert data_utils.remove_player("X", 1) == 0
        with patch('cogs.data_utils._bot_db') as mock_db:
            mock_db.remove_player.return_value = 1
            assert data_utils.remove_player("X", 1) == 1

    def test_edit_calls_remove_then_add(self):
        """Edit flow removes first, then adds — in that order."""
        call_order = []
        cog = lists_cog.Lists(None)
        ctx = MagicMock()
        ctx.author.guild_permissions.administrator = True
        ctx.guild.get_member.return_value = None
        ctx.guild.id = 777
        ctx.send = AsyncMock()

        def track_remove(*a, **kw):
            call_order.append("remove")
            return 1

        def track_add(*a, **kw):
            call_order.append("add")

        with patch('cogs.lists_cog.remove_player', side_effect=track_remove), \
             patch('cogs.lists_cog.add_player', side_effect=track_add), \
             patch('cogs.lists_cog.load_guild_data', return_value=True):
            _run(cog.deadlist.callback(cog, ctx, "edit", "JohnDoe", "village", role="Doc"))

        assert call_order == ["remove", "add"]
