"""Test generation — generates pytest test files for untested cogs/commands."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from ._path_utils import file_to_module, project_root
from .auditor import discover_all
from .coverage import analyze_coverage

TESTS_DIR = Path(__file__).parent / "tests"
PROJECT_DIR = project_root()


def _module_import_for(cog_file: str) -> tuple[str, str]:
    """Convert a cog file path to a Python import path. Returns (import_line, import_alias)."""
    p = Path(cog_file)
    stem = p.stem
    mod_name = file_to_module(cog_file)
    if "." in mod_name:
        package = mod_name.rsplit(".", 1)[0]
        return f"from {package} import {stem}", stem
    return f"import {stem}", stem


def generate_cog_test(canonical: str) -> str | None:
    """Generate a pytest test file for an untested cog. Returns the file content or None."""
    cogs = discover_all()
    coverage = analyze_coverage()

    if canonical not in cogs:
        return None

    cog = cogs[canonical]
    cov = coverage.get(canonical)

    # Skip if well-tested
    if cov and cov.estimated_overall >= 50:
        return None

    # Build import
    import_line, mod_name = _module_import_for(cog.file)

    # Determine class reference for hasattr checks
    if cog.cog_class:
        class_ref = f"{mod_name}.{cog.cog_class}"
    else:
        class_ref = mod_name  # module-level functions

    lines = [
        f'"""Tests for {cog.name} cog (auto-generated by testing framework)."""',
        "",
        "import pytest",
        "from unittest.mock import MagicMock, AsyncMock, patch",
        "import discord",
        "",
        import_line,
        "",
        "",
    ]

    if cog.cog_class:
        class_name = f"Test{cog.cog_class}"
    else:
        # Derive class name from canonical
        parts = canonical.split("_")
        class_name = f"Test{''.join(p.title() for p in parts)}Commands"

    lines.append(f"class {class_name}:")
    lines.append('    """Validate all commands exist and have required metadata."""')
    lines.append("")

    # Add a test for each command
    all_cmds = cog.prefix_commands + cog.slash_commands
    for cmd in all_cmds:
        lines.append(f"    def test_{cmd}_exists(self):")
        lines.append(f'        """Verify {cmd} command exists on the cog."""')
        lines.append(f"        assert hasattr({class_ref}, '{cmd}')")
        lines.append("")
        lines.append(f"    def test_{cmd}_has_help(self):")
        lines.append(f'        """Verify {cmd} command has help text."""')
        lines.append(f"        method = getattr({class_ref}, '{cmd}')")
        lines.append(f"        doc = getattr(method, 'help', None) or getattr(method, '__doc__', None)")
        lines.append(f"        assert doc is not None and len(doc.strip()) > 0")
        lines.append("")

    # Add view tests — skip discord.ui.View subclasses (need event loop)
    for view in cog.views:
        lines.append(f"    def test_{view.lower()}_defined(self):")
        lines.append(f'        """Verify {view} view is defined in the module."""')
        lines.append(f"        assert hasattr({class_ref.rsplit('.', 1)[0]}, '{view}')")
        lines.append("")

    return "\n".join(lines)


def generate_all_missing_tests() -> list[str]:
    """Generate test files for all untested cogs. Returns list of created filenames."""
    cogs = discover_all()
    coverage = analyze_coverage()
    created = []

    for canonical, cog in cogs.items():
        cov = coverage.get(canonical)
        if cov and cov.estimated_overall >= 50:
            continue
        # Skip cogs with no commands and no methods
        if not cog.prefix_commands and not cog.slash_commands and cog.total_methods == 0:
            continue

        content = generate_cog_test(canonical)
        if content is None:
            continue

        filepath = TESTS_DIR / f"test_{canonical}.py"
        # Don't overwrite existing tests
        if filepath.exists():
            continue

        os.makedirs(str(TESTS_DIR), exist_ok=True)
        filepath.write_text(content, encoding="utf-8")
        created.append(filepath.name)

    return created
